/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Conflict
 */
export type CreateListSlugConflictErrorData = {
  statusCode: operations.CreateListConflictStatusCode;
  type: operations.CreateListConflictType;
  code: operations.CreateListConflictCode;
  message: string;
};

/**
 * Conflict
 */
export class CreateListSlugConflictError extends AttioBaseError {
  type: operations.CreateListConflictType;
  code: operations.CreateListConflictCode;

  /** The original data that was passed to this error instance. */
  data$: CreateListSlugConflictErrorData;

  constructor(
    err: CreateListSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateListSlugConflictError";
  }
}

/**
 * Not Found
 */
export type CreateListNotFoundErrorData = {
  statusCode: operations.CreateListNotFoundStatusCode;
  type: operations.CreateListNotFoundType;
  code: operations.CreateListNotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class CreateListNotFoundError extends AttioBaseError {
  type: operations.CreateListNotFoundType;
  code: operations.CreateListNotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: CreateListNotFoundErrorData;

  constructor(
    err: CreateListNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateListNotFoundError";
  }
}

/**
 * Forbidden
 */
export type BillingErrorData = {
  statusCode: operations.CreateListForbiddenStatusCode;
  type: operations.CreateListForbiddenType;
  code: operations.CreateListCodeBillingError;
  message: string;
};

/**
 * Forbidden
 */
export class BillingError extends AttioBaseError {
  type: operations.CreateListForbiddenType;
  code: operations.CreateListCodeBillingError;

  /** The original data that was passed to this error instance. */
  data$: BillingErrorData;

  constructor(
    err: BillingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "BillingError";
  }
}

/**
 * Bad Request
 */
export type CreateListValueNotFoundErrorData = {
  statusCode: operations.CreateListBadRequestStatusCode;
  type: operations.CreateListBadRequestType;
  code: operations.CreateListCodeValueNotFound;
  message: string;
};

/**
 * Bad Request
 */
export class CreateListValueNotFoundError extends AttioBaseError {
  type: operations.CreateListBadRequestType;
  code: operations.CreateListCodeValueNotFound;

  /** The original data that was passed to this error instance. */
  data$: CreateListValueNotFoundErrorData;

  constructor(
    err: CreateListValueNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateListValueNotFoundError";
  }
}

/** @internal */
export const CreateListSlugConflictError$inboundSchema: z.ZodMiniType<
  CreateListSlugConflictError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.CreateListConflictStatusCode$inboundSchema,
    type: operations.CreateListConflictType$inboundSchema,
    code: operations.CreateListConflictCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateListSlugConflictError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateListNotFoundError$inboundSchema: z.ZodMiniType<
  CreateListNotFoundError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.CreateListNotFoundStatusCode$inboundSchema,
    type: operations.CreateListNotFoundType$inboundSchema,
    code: operations.CreateListNotFoundCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateListNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BillingError$inboundSchema: z.ZodMiniType<BillingError, unknown> =
  z.pipe(
    z.object({
      status_code: operations.CreateListForbiddenStatusCode$inboundSchema,
      type: operations.CreateListForbiddenType$inboundSchema,
      code: operations.CreateListCodeBillingError$inboundSchema,
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new BillingError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const CreateListValueNotFoundError$inboundSchema: z.ZodMiniType<
  CreateListValueNotFoundError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.CreateListBadRequestStatusCode$inboundSchema,
    type: operations.CreateListBadRequestType$inboundSchema,
    code: operations.CreateListCodeValueNotFound$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateListValueNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
