/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Conflict
 */
export type CreateAttributeStatusSlugConflictErrorData = {
  type: "invalid_request_error";
  statusCode: 409;
  code: "slug_conflict";
  message: string;
};

/**
 * Conflict
 */
export class CreateAttributeStatusSlugConflictError extends AttioBaseError {
  type: "invalid_request_error";
  code: "slug_conflict";

  /** The original data that was passed to this error instance. */
  data$: CreateAttributeStatusSlugConflictErrorData;

  constructor(
    err: CreateAttributeStatusSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateAttributeStatusSlugConflictError";
  }
}

/**
 * Not Found
 */
export type CreateAttributeStatusNotFoundErrorData = {
  type: "invalid_request_error";
  statusCode: 404;
  code: "not_found";
  message: string;
};

/**
 * Not Found
 */
export class CreateAttributeStatusNotFoundError extends AttioBaseError {
  type: "invalid_request_error";
  code: "not_found";

  /** The original data that was passed to this error instance. */
  data$: CreateAttributeStatusNotFoundErrorData;

  constructor(
    err: CreateAttributeStatusNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateAttributeStatusNotFoundError";
  }
}

/**
 * Forbidden
 */
export type CreateAttributeStatusAuthErrorData = {
  type: "auth_error";
  statusCode: 403;
  code: string;
  message: string;
};

/**
 * Forbidden
 */
export class CreateAttributeStatusAuthError extends AttioBaseError {
  type: "auth_error";
  code: string;

  /** The original data that was passed to this error instance. */
  data$: CreateAttributeStatusAuthErrorData;

  constructor(
    err: CreateAttributeStatusAuthErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateAttributeStatusAuthError";
  }
}

/**
 * Bad Request
 */
export type CreateAttributeStatusValidationTypeErrorData = {
  type: "invalid_request_error";
  statusCode: 400;
  code: "validation_type";
  message: string;
};

/**
 * Bad Request
 */
export class CreateAttributeStatusValidationTypeError extends AttioBaseError {
  type: "invalid_request_error";
  code: "validation_type";

  /** The original data that was passed to this error instance. */
  data$: CreateAttributeStatusValidationTypeErrorData;

  constructor(
    err: CreateAttributeStatusValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateAttributeStatusValidationTypeError";
  }
}

/** @internal */
export const CreateAttributeStatusSlugConflictError$inboundSchema:
  z.ZodMiniType<CreateAttributeStatusSlugConflictError, unknown> = z.pipe(
    z.object({
      type: types.literal("invalid_request_error"),
      status_code: types.literal(409),
      code: types.literal("slug_conflict"),
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new CreateAttributeStatusSlugConflictError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const CreateAttributeStatusNotFoundError$inboundSchema: z.ZodMiniType<
  CreateAttributeStatusNotFoundError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("invalid_request_error"),
    status_code: types.literal(404),
    code: types.literal("not_found"),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateAttributeStatusNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateAttributeStatusAuthError$inboundSchema: z.ZodMiniType<
  CreateAttributeStatusAuthError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("auth_error"),
    status_code: types.literal(403),
    code: types.string(),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateAttributeStatusAuthError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateAttributeStatusValidationTypeError$inboundSchema:
  z.ZodMiniType<CreateAttributeStatusValidationTypeError, unknown> = z.pipe(
    z.object({
      type: types.literal("invalid_request_error"),
      status_code: types.literal(400),
      code: types.literal("validation_type"),
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new CreateAttributeStatusValidationTypeError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
