/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Content Too Large
 */
export type CreateNoteValidationTypeErrorData = {
  type: "invalid_request_error";
  statusCode: 413;
  code: "validation_type";
  message: string;
};

/**
 * Content Too Large
 */
export class CreateNoteValidationTypeError extends AttioBaseError {
  type: "invalid_request_error";
  code: "validation_type";

  /** The original data that was passed to this error instance. */
  data$: CreateNoteValidationTypeErrorData;

  constructor(
    err: CreateNoteValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateNoteValidationTypeError";
  }
}

/**
 * Not Found
 */
export type CreateNoteNotFoundErrorData = {
  type: "invalid_request_error";
  statusCode: 404;
  code: "not_found";
  message: string;
};

/**
 * Not Found
 */
export class CreateNoteNotFoundError extends AttioBaseError {
  type: "invalid_request_error";
  code: "not_found";

  /** The original data that was passed to this error instance. */
  data$: CreateNoteNotFoundErrorData;

  constructor(
    err: CreateNoteNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "CreateNoteNotFoundError";
  }
}

/** @internal */
export const CreateNoteValidationTypeError$inboundSchema: z.ZodMiniType<
  CreateNoteValidationTypeError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("invalid_request_error"),
    status_code: types.literal(413),
    code: types.literal("validation_type"),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateNoteValidationTypeError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const CreateNoteNotFoundError$inboundSchema: z.ZodMiniType<
  CreateNoteNotFoundError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("invalid_request_error"),
    status_code: types.literal(404),
    code: types.literal("not_found"),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new CreateNoteNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
