/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Not Found
 */
export type DeleteTaskNotFoundErrorData = {
  statusCode: operations.DeleteTaskStatusCode;
  type: operations.DeleteTaskType;
  code: operations.DeleteTaskCode;
  message: string;
};

/**
 * Not Found
 */
export class DeleteTaskNotFoundError extends AttioBaseError {
  type: operations.DeleteTaskType;
  code: operations.DeleteTaskCode;

  /** The original data that was passed to this error instance. */
  data$: DeleteTaskNotFoundErrorData;

  constructor(
    err: DeleteTaskNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "DeleteTaskNotFoundError";
  }
}

/** @internal */
export const DeleteTaskNotFoundError$inboundSchema: z.ZodMiniType<
  DeleteTaskNotFoundError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.DeleteTaskStatusCode$inboundSchema,
    type: operations.DeleteTaskType$inboundSchema,
    code: operations.DeleteTaskCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new DeleteTaskNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
