/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioError } from "./attio-error.js";

/**
 * Not Found
 */
export type GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData = {
  statusCode: number;
  type: operations.GetV2WorkspaceMembersWorkspaceMemberIdType;
  code: operations.GetV2WorkspaceMembersWorkspaceMemberIdCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError
  extends AttioError
{
  type: operations.GetV2WorkspaceMembersWorkspaceMemberIdType;
  code: operations.GetV2WorkspaceMembersWorkspaceMemberIdCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData;

  constructor(
    err: GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError";
  }
}

/** @internal */
export const GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError$inboundSchema:
  z.ZodMiniType<GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError, unknown> =
    z.pipe(
      z.object({
        status_code: types.number(),
        type:
          operations.GetV2WorkspaceMembersWorkspaceMemberIdType$inboundSchema,
        code:
          operations.GetV2WorkspaceMembersWorkspaceMemberIdCode$inboundSchema,
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        const remapped = remap$(v, {
          "status_code": "statusCode",
        });

        return new GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError(
          remapped,
          { request: v.request$, response: v.response$, body: v.body$ },
        );
      }),
    );
