/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Not Found
 */
export type GetWebhookNotFoundErrorData = {
  statusCode: operations.GetWebhookStatusCode;
  type: operations.GetWebhookType;
  code: operations.GetWebhookCode;
  message: string;
};

/**
 * Not Found
 */
export class GetWebhookNotFoundError extends AttioBaseError {
  type: operations.GetWebhookType;
  code: operations.GetWebhookCode;

  /** The original data that was passed to this error instance. */
  data$: GetWebhookNotFoundErrorData;

  constructor(
    err: GetWebhookNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetWebhookNotFoundError";
  }
}

/** @internal */
export const GetWebhookNotFoundError$inboundSchema: z.ZodMiniType<
  GetWebhookNotFoundError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.GetWebhookStatusCode$inboundSchema,
    type: operations.GetWebhookType$inboundSchema,
    code: operations.GetWebhookCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetWebhookNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
