/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioError } from "./attio-error.js";

/**
 * Not Found
 */
export type PostV2ObjectsObjectRecordsNotFoundErrorData = {
  statusCode: number;
  type: operations.PostV2ObjectsObjectRecordsNotFoundType;
  code: operations.PostV2ObjectsObjectRecordsNotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ObjectsObjectRecordsNotFoundError extends AttioError {
  type: operations.PostV2ObjectsObjectRecordsNotFoundType;
  code: operations.PostV2ObjectsObjectRecordsNotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsNotFoundErrorData;

  constructor(
    err: PostV2ObjectsObjectRecordsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2ObjectsObjectRecordsValueNotFoundErrorData = {
  statusCode: number;
  type: operations.PostV2ObjectsObjectRecordsBadRequestType;
  code: operations.PostV2ObjectsObjectRecordsCodeValueNotFound;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ObjectsObjectRecordsValueNotFoundError extends AttioError {
  type: operations.PostV2ObjectsObjectRecordsBadRequestType;
  code: operations.PostV2ObjectsObjectRecordsCodeValueNotFound;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsValueNotFoundErrorData;

  constructor(
    err: PostV2ObjectsObjectRecordsValueNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsValueNotFoundError";
  }
}

/** @internal */
export const PostV2ObjectsObjectRecordsNotFoundError$inboundSchema:
  z.ZodMiniType<PostV2ObjectsObjectRecordsNotFoundError, unknown> = z.pipe(
    z.object({
      status_code: types.number(),
      type: operations.PostV2ObjectsObjectRecordsNotFoundType$inboundSchema,
      code: operations.PostV2ObjectsObjectRecordsNotFoundCode$inboundSchema,
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );

/** @internal */
export const PostV2ObjectsObjectRecordsValueNotFoundError$inboundSchema:
  z.ZodMiniType<PostV2ObjectsObjectRecordsValueNotFoundError, unknown> = z.pipe(
    z.object({
      status_code: types.number(),
      type: operations.PostV2ObjectsObjectRecordsBadRequestType$inboundSchema,
      code:
        operations.PostV2ObjectsObjectRecordsCodeValueNotFound$inboundSchema,
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsValueNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
