/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Not Found
 */
export type PostV2ListsListEntriesQueryNotFoundErrorData = {
  statusCode: number;
  type: operations.PostV2ListsListEntriesQueryNotFoundType;
  code: operations.PostV2ListsListEntriesQueryCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ListsListEntriesQueryNotFoundError extends AttioBaseError {
  type: operations.PostV2ListsListEntriesQueryNotFoundType;
  code: operations.PostV2ListsListEntriesQueryCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ListsListEntriesQueryNotFoundErrorData;

  constructor(
    err: PostV2ListsListEntriesQueryNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ListsListEntriesQueryNotFoundError";
  }
}

/** @internal */
export const PostV2ListsListEntriesQueryNotFoundError$inboundSchema:
  z.ZodMiniType<PostV2ListsListEntriesQueryNotFoundError, unknown> = z.pipe(
    z.object({
      status_code: types.number(),
      type: operations.PostV2ListsListEntriesQueryNotFoundType$inboundSchema,
      code: operations.PostV2ListsListEntriesQueryCode$inboundSchema,
      message: types.string(),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ListsListEntriesQueryNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
