/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioError } from "./attio-error.js";

/**
 * Not Found
 */
export type PutV2ObjectsObjectRecordsRecordIdNotFoundErrorData = {
  statusCode: number;
  type: operations.PutV2ObjectsObjectRecordsRecordIdNotFoundType;
  code: operations.PutV2ObjectsObjectRecordsRecordIdNotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PutV2ObjectsObjectRecordsRecordIdNotFoundError extends AttioError {
  type: operations.PutV2ObjectsObjectRecordsRecordIdNotFoundType;
  code: operations.PutV2ObjectsObjectRecordsRecordIdNotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PutV2ObjectsObjectRecordsRecordIdNotFoundErrorData;

  constructor(
    err: PutV2ObjectsObjectRecordsRecordIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PutV2ObjectsObjectRecordsRecordIdNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PutV2ObjectsObjectRecordsRecordIdMissingValueErrorData = {
  statusCode: number;
  type: operations.PutV2ObjectsObjectRecordsRecordIdBadRequestType;
  code: operations.PutV2ObjectsObjectRecordsRecordIdCodeMissingValue;
  message: string;
};

/**
 * Bad Request
 */
export class PutV2ObjectsObjectRecordsRecordIdMissingValueError
  extends AttioError
{
  type: operations.PutV2ObjectsObjectRecordsRecordIdBadRequestType;
  code: operations.PutV2ObjectsObjectRecordsRecordIdCodeMissingValue;

  /** The original data that was passed to this error instance. */
  data$: PutV2ObjectsObjectRecordsRecordIdMissingValueErrorData;

  constructor(
    err: PutV2ObjectsObjectRecordsRecordIdMissingValueErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PutV2ObjectsObjectRecordsRecordIdMissingValueError";
  }
}

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdNotFoundError$inboundSchema:
  z.ZodMiniType<PutV2ObjectsObjectRecordsRecordIdNotFoundError, unknown> = z
    .pipe(
      z.object({
        status_code: types.number(),
        type:
          operations
            .PutV2ObjectsObjectRecordsRecordIdNotFoundType$inboundSchema,
        code:
          operations
            .PutV2ObjectsObjectRecordsRecordIdNotFoundCode$inboundSchema,
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        const remapped = remap$(v, {
          "status_code": "statusCode",
        });

        return new PutV2ObjectsObjectRecordsRecordIdNotFoundError(remapped, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      }),
    );

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdMissingValueError$inboundSchema:
  z.ZodMiniType<PutV2ObjectsObjectRecordsRecordIdMissingValueError, unknown> = z
    .pipe(
      z.object({
        status_code: types.number(),
        type:
          operations
            .PutV2ObjectsObjectRecordsRecordIdBadRequestType$inboundSchema,
        code:
          operations
            .PutV2ObjectsObjectRecordsRecordIdCodeMissingValue$inboundSchema,
        message: types.string(),
        request$: z.custom<Request>(x => x instanceof Request),
        response$: z.custom<Response>(x => x instanceof Response),
        body$: z.string(),
      }),
      z.transform((v) => {
        const remapped = remap$(v, {
          "status_code": "statusCode",
        });

        return new PutV2ObjectsObjectRecordsRecordIdMissingValueError(
          remapped,
          { request: v.request$, response: v.response$, body: v.body$ },
        );
      }),
    );
