/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Not Found
 */
export type UpdateEntryNotFoundErrorData = {
  statusCode: operations.UpdateEntryNotFoundStatusCode;
  type: operations.UpdateEntryNotFoundType;
  code: operations.UpdateEntryNotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class UpdateEntryNotFoundError extends AttioBaseError {
  type: operations.UpdateEntryNotFoundType;
  code: operations.UpdateEntryNotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: UpdateEntryNotFoundErrorData;

  constructor(
    err: UpdateEntryNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "UpdateEntryNotFoundError";
  }
}

/**
 * Bad Request
 */
export type UpdateEntryImmutableValueErrorData = {
  statusCode: operations.UpdateEntryBadRequestStatusCode;
  type: operations.UpdateEntryBadRequestType;
  code: operations.UpdateEntryCodeImmutableValue;
  message: string;
};

/**
 * Bad Request
 */
export class UpdateEntryImmutableValueError extends AttioBaseError {
  type: operations.UpdateEntryBadRequestType;
  code: operations.UpdateEntryCodeImmutableValue;

  /** The original data that was passed to this error instance. */
  data$: UpdateEntryImmutableValueErrorData;

  constructor(
    err: UpdateEntryImmutableValueErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "UpdateEntryImmutableValueError";
  }
}

/** @internal */
export const UpdateEntryNotFoundError$inboundSchema: z.ZodMiniType<
  UpdateEntryNotFoundError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.UpdateEntryNotFoundStatusCode$inboundSchema,
    type: operations.UpdateEntryNotFoundType$inboundSchema,
    code: operations.UpdateEntryNotFoundCode$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new UpdateEntryNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UpdateEntryImmutableValueError$inboundSchema: z.ZodMiniType<
  UpdateEntryImmutableValueError,
  unknown
> = z.pipe(
  z.object({
    status_code: operations.UpdateEntryBadRequestStatusCode$inboundSchema,
    type: operations.UpdateEntryBadRequestType$inboundSchema,
    code: operations.UpdateEntryCodeImmutableValue$inboundSchema,
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new UpdateEntryImmutableValueError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
