/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { AttioBaseError } from "./attio-base-error.js";

/**
 * Not Found
 */
export type UpdateAppendRecordNotFoundErrorData = {
  type: "invalid_request_error";
  statusCode: 404;
  code: "not_found";
  message: string;
};

/**
 * Not Found
 */
export class UpdateAppendRecordNotFoundError extends AttioBaseError {
  type: "invalid_request_error";
  code: "not_found";

  /** The original data that was passed to this error instance. */
  data$: UpdateAppendRecordNotFoundErrorData;

  constructor(
    err: UpdateAppendRecordNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "UpdateAppendRecordNotFoundError";
  }
}

/**
 * Bad Request
 */
export type UpdateAppendRecordMissingValueErrorData = {
  type: "invalid_request_error";
  statusCode: 400;
  code: "missing_value";
  message: string;
};

/**
 * Bad Request
 */
export class UpdateAppendRecordMissingValueError extends AttioBaseError {
  type: "invalid_request_error";
  code: "missing_value";

  /** The original data that was passed to this error instance. */
  data$: UpdateAppendRecordMissingValueErrorData;

  constructor(
    err: UpdateAppendRecordMissingValueErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "UpdateAppendRecordMissingValueError";
  }
}

/** @internal */
export const UpdateAppendRecordNotFoundError$inboundSchema: z.ZodMiniType<
  UpdateAppendRecordNotFoundError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("invalid_request_error"),
    status_code: types.literal(404),
    code: types.literal("not_found"),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new UpdateAppendRecordNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const UpdateAppendRecordMissingValueError$inboundSchema: z.ZodMiniType<
  UpdateAppendRecordMissingValueError,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("invalid_request_error"),
    status_code: types.literal(400),
    code: types.literal("missing_value"),
    message: types.string(),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new UpdateAppendRecordMissingValueError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
