/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { activitiesDeleteV2ActivitiesActivity } from "../funcs/activities-delete-v2-activities-activity.js";
import { activitiesGetV2ActivitiesActivity } from "../funcs/activities-get-v2-activities-activity.js";
import { activitiesGetV2Activities } from "../funcs/activities-get-v2-activities.js";
import { activitiesPatchV2ActivitiesActivity } from "../funcs/activities-patch-v2-activities-activity.js";
import { activitiesPostV2Activities } from "../funcs/activities-post-v2-activities.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Activities extends ClientSDK {
  /**
   * List activities
   *
   * @remarks
   * Lists all system-defined and user-defined activities in your workspace.
   *
   * This endpoint is in alpha and may be subject to breaking changes as we gather feedback.
   *
   * Required scopes: `activity_configuration:read`.
   */
  async getV2Activities(
    request?: operations.GetV2ActivitiesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV2ActivitiesResponse> {
    return unwrapAsync(activitiesGetV2Activities(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an activity
   *
   * @remarks
   * Creates a new custom activity in your workspace.
   *
   * This endpoint is in alpha and may be subject to breaking changes as we gather feedback.
   *
   * Required scopes: `activity_configuration:read-write`.
   */
  async postV2Activities(
    request: operations.PostV2ActivitiesRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2ActivitiesResponse> {
    return unwrapAsync(activitiesPostV2Activities(
      this,
      request,
      options,
    ));
  }

  /**
   * Get an activity
   *
   * @remarks
   * Gets a single activity by its `activity_id` or slug.
   *
   * This endpoint is in alpha and may be subject to breaking changes as we gather feedback.
   *
   * Required scopes: `activity_configuration:read`.
   */
  async getV2ActivitiesActivity(
    request: operations.GetV2ActivitiesActivityRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2ActivitiesActivityResponse> {
    return unwrapAsync(activitiesGetV2ActivitiesActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an activity
   *
   * @remarks
   * Deletes a single activity by its `activity_id` or slug, along with all of its records. Archived activities can also be deleted.
   *
   * This endpoint should be used with caution as it has the potential to remove a large amount of potentially valuable data.
   *
   * This endpoint is in alpha and may be subject to breaking changes as we gather feedback.
   *
   * Required scopes: `activity_configuration:read-write`, `activity_record:read-write`.
   */
  async deleteV2ActivitiesActivity(
    request: operations.DeleteV2ActivitiesActivityRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV2ActivitiesActivityResponse> {
    return unwrapAsync(activitiesDeleteV2ActivitiesActivity(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an activity
   *
   * @remarks
   * Updates a single activity by its `activity_id` or slug. The schema an activity extends is fixed after creation, so `extends` cannot be changed.
   *
   * This endpoint is in alpha and may be subject to breaking changes as we gather feedback.
   *
   * Required scopes: `activity_configuration:read-write`.
   */
  async patchV2ActivitiesActivity(
    request: operations.PatchV2ActivitiesActivityRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV2ActivitiesActivityResponse> {
    return unwrapAsync(activitiesPatchV2ActivitiesActivity(
      this,
      request,
      options,
    ));
  }
}
