/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesCreate } from "../funcs/files-create.js";
import { filesDelete } from "../funcs/files-delete.js";
import { filesDownload } from "../funcs/files-download.js";
import { filesGet } from "../funcs/files-get.js";
import { filesList } from "../funcs/files-list.js";
import { filesUpload } from "../funcs/files-upload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Files extends ClientSDK {
  /**
   * List files
   *
   * @remarks
   * Lists internal files, externally connected files and folders across the workspace. Optional query parameters may be provided to filter results by object, record, storage provider or parent folder.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `object_configuration:read`, `record_permission:read`, `file:read`.
   */
  async list(
    request: operations.ListFilesRequest,
    options?: RequestOptions,
  ): Promise<operations.ListFilesResponse> {
    return unwrapAsync(filesList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a folder
   *
   * @remarks
   * Creates a native folder entry or a connected file/folder entry on an object record.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `file:read-write`, `object_configuration:read`, `record_permission:read`.
   */
  async create(
    request: operations.CreateFileRequest,
    options?: RequestOptions,
  ): Promise<operations.CreateFileResponse> {
    return unwrapAsync(filesCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Upload a file
   *
   * @remarks
   * Uploads a file to native Attio storage for a record. Send multipart/form-data with a single binary field named `file` together with the body fields `object`, `record_id`, and optional `parent_folder_id`. Maximum file size is 50 MB.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `file:read-write`, `object_configuration:read`, `record_permission:read`.
   */
  async upload(
    request: operations.UploadFileRequest,
    options?: RequestOptions,
  ): Promise<operations.UploadFileResponse> {
    return unwrapAsync(filesUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a file
   *
   * @remarks
   * Get a single file entry by ID.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `file:read`, `object_configuration:read`, `record_permission:read`.
   */
  async get(
    request: operations.GetFileRequest,
    options?: RequestOptions,
  ): Promise<operations.GetFileResponse> {
    return unwrapAsync(filesGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a file
   *
   * @remarks
   * Delete a single file by ID. Deleting a folder will delete all of its descendants.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `file:read-write`, `object_configuration:read`, `record_permission:read`.
   */
  async delete(
    request: operations.DeleteFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteFileResponse> {
    return unwrapAsync(filesDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Download a file
   *
   * @remarks
   * Downloads a file by redirecting to a signed URL.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `object_configuration:read`, `record_permission:read`, `file:read`.
   */
  async download(
    request: operations.DownloadFileRequest,
    options?: RequestOptions,
  ): Promise<operations.DownloadFileResponse> {
    return unwrapAsync(filesDownload(
      this,
      request,
      options,
    ));
  }
}
