/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { recordsDeleteV2ObjectsObjectRecordsRecordId } from "../funcs/records-delete-v2-objects-object-records-record-id.js";
import { recordsGetV2ObjectsObjectRecordsRecordIdAttributesAttributeValues } from "../funcs/records-get-v2-objects-object-records-record-id-attributes-attribute-values.js";
import { recordsGetV2ObjectsObjectRecordsRecordIdEntries } from "../funcs/records-get-v2-objects-object-records-record-id-entries.js";
import { recordsGetV2ObjectsObjectRecordsRecordId } from "../funcs/records-get-v2-objects-object-records-record-id.js";
import { recordsPatchV2ObjectsObjectRecordsRecordId } from "../funcs/records-patch-v2-objects-object-records-record-id.js";
import { recordsPostV2ObjectsObjectRecordsQuery } from "../funcs/records-post-v2-objects-object-records-query.js";
import { recordsPostV2ObjectsObjectRecords } from "../funcs/records-post-v2-objects-object-records.js";
import { recordsPostV2ObjectsRecordsSearch } from "../funcs/records-post-v2-objects-records-search.js";
import { recordsPutV2ObjectsObjectRecordsRecordId } from "../funcs/records-put-v2-objects-object-records-record-id.js";
import { recordsPutV2ObjectsObjectRecords } from "../funcs/records-put-v2-objects-object-records.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Records extends ClientSDK {
  /**
   * List records
   *
   * @remarks
   * Lists people, company or other records, with the option to filter and sort results.
   *
   * Required scopes: `record_permission:read`, `object_configuration:read`.
   */
  async postV2ObjectsObjectRecordsQuery(
    request: operations.PostV2ObjectsObjectRecordsQueryRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2ObjectsObjectRecordsQueryResponse> {
    return unwrapAsync(recordsPostV2ObjectsObjectRecordsQuery(
      this,
      request,
      options,
    ));
  }

  /**
   * Assert a record
   *
   * @remarks
   * Use this endpoint to create or update people, companies and other records. A matching attribute is used to search for existing records. If a record is found with the same value for the matching attribute, that record will be updated. If no record with the same value for the matching attribute is found, a new record will be created instead. If you would like to avoid matching, please use the [Create record endpoint](/rest-api/endpoint-reference/records/create-a-record).
   *
   * If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be either created or deleted as necessary to match the list of supplied values.
   *
   * Required scopes: `record_permission:read-write`, `object_configuration:read`.
   */
  async putV2ObjectsObjectRecords(
    request: operations.PutV2ObjectsObjectRecordsRequest,
    options?: RequestOptions,
  ): Promise<operations.PutV2ObjectsObjectRecordsResponse> {
    return unwrapAsync(recordsPutV2ObjectsObjectRecords(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a record
   *
   * @remarks
   * Creates a new person, company or other record. This endpoint will throw on conflicts of unique attributes. If you would prefer to update records on conflicts, please use the [Assert record endpoint](/rest-api/endpoint-reference/records/assert-a-record) instead.
   *
   * Required scopes: `record_permission:read-write`, `object_configuration:read`.
   */
  async postV2ObjectsObjectRecords(
    request: operations.PostV2ObjectsObjectRecordsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2ObjectsObjectRecordsResponse> {
    return unwrapAsync(recordsPostV2ObjectsObjectRecords(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a record
   *
   * @remarks
   * Gets a single person, company or other record by its `record_id`.
   *
   * Required scopes: `record_permission:read`, `object_configuration:read`.
   */
  async getV2ObjectsObjectRecordsRecordId(
    request: operations.GetV2ObjectsObjectRecordsRecordIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2ObjectsObjectRecordsRecordIdResponse> {
    return unwrapAsync(recordsGetV2ObjectsObjectRecordsRecordId(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a record (overwrite multiselect values)
   *
   * @remarks
   * Use this endpoint to update people, companies, and other records by `record_id`. If the update payload includes multiselect attributes, the values supplied will overwrite/remove the list of values that already exist (if any). Use the `PATCH` endpoint to append multiselect values without removing those that already exist.
   *
   * Required scopes: `record_permission:read-write`, `object_configuration:read`.
   */
  async putV2ObjectsObjectRecordsRecordId(
    request: operations.PutV2ObjectsObjectRecordsRecordIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PutV2ObjectsObjectRecordsRecordIdResponse> {
    return unwrapAsync(recordsPutV2ObjectsObjectRecordsRecordId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a record
   *
   * @remarks
   * Deletes a single record (e.g. a company or person) by ID.
   *
   * Required scopes: `object_configuration:read`, `record_permission:read-write`.
   */
  async deleteV2ObjectsObjectRecordsRecordId(
    request: operations.DeleteV2ObjectsObjectRecordsRecordIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV2ObjectsObjectRecordsRecordIdResponse> {
    return unwrapAsync(recordsDeleteV2ObjectsObjectRecordsRecordId(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a record (append multiselect values)
   *
   * @remarks
   * Use this endpoint to update people, companies, and other records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the `PUT` endpoint to overwrite or remove multiselect attribute values.
   *
   * Required scopes: `record_permission:read-write`, `object_configuration:read`.
   */
  async patchV2ObjectsObjectRecordsRecordId(
    request: operations.PatchV2ObjectsObjectRecordsRecordIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV2ObjectsObjectRecordsRecordIdResponse> {
    return unwrapAsync(recordsPatchV2ObjectsObjectRecordsRecordId(
      this,
      request,
      options,
    ));
  }

  /**
   * List record attribute values
   *
   * @remarks
   * Gets all values for a given attribute on a record. Historic values can be queried using the `show_historic` query param. Historic values cannot be queried on COMINT (Communication Intelligence) or enriched attributes and the endpoint will return a 400 error if this is attempted. Historic values are sorted from oldest to newest (by `active_from`). Some attributes are subject to billing status and will return an empty array of values if theworkspace being queried does not have the required billing flag enabled.
   *
   * Required scopes: `record_permission:read`, `object_configuration:read`.
   */
  async getV2ObjectsObjectRecordsRecordIdAttributesAttributeValues(
    request:
      operations.GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesRequest,
    options?: RequestOptions,
  ): Promise<
    operations.GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesResponse
  > {
    return unwrapAsync(
      recordsGetV2ObjectsObjectRecordsRecordIdAttributesAttributeValues(
        this,
        request,
        options,
      ),
    );
  }

  /**
   * List record entries
   *
   * @remarks
   * List all entries, across all lists, for which this record is the parent.
   *
   * Required scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.
   */
  async getV2ObjectsObjectRecordsRecordIdEntries(
    request: operations.GetV2ObjectsObjectRecordsRecordIdEntriesRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2ObjectsObjectRecordsRecordIdEntriesResponse> {
    return unwrapAsync(recordsGetV2ObjectsObjectRecordsRecordIdEntries(
      this,
      request,
      options,
    ));
  }

  /**
   * Search records
   *
   * @remarks
   * The search records endpoint provides a convenient way to fuzzy search for records across one or more objects.
   * The matching strategy employed in this endpoint follows the in-product strategy and will match names, domains, emails, phone numbers and social handles on people and companies, and labels on all other objects.
   * Please note, results returned from this endpoint are eventually consistent. For results which are guaranteed to be up to date, please use the record query endpoint instead.
   *
   * This endpoint is in beta. We will aim to avoid breaking changes, but small updates may be made as we roll out to more users.
   *
   * Required scopes: `record_permission:read`, `object_configuration:read`.
   */
  async postV2ObjectsRecordsSearch(
    request: operations.PostV2ObjectsRecordsSearchRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2ObjectsRecordsSearchResponse> {
    return unwrapAsync(recordsPostV2ObjectsRecordsSearch(
      this,
      request,
      options,
    ));
  }
}
