/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksDeleteV2WebhooksWebhookId } from "../funcs/webhooks-delete-v2-webhooks-webhook-id.js";
import { webhooksGetV2WebhooksWebhookId } from "../funcs/webhooks-get-v2-webhooks-webhook-id.js";
import { webhooksGetV2Webhooks } from "../funcs/webhooks-get-v2-webhooks.js";
import { webhooksPatchV2WebhooksWebhookId } from "../funcs/webhooks-patch-v2-webhooks-webhook-id.js";
import { webhooksPostV2Webhooks } from "../funcs/webhooks-post-v2-webhooks.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List webhooks
   *
   * @remarks
   * Get all of the webhooks in your workspace.
   *
   * Required scopes: `webhook:read`.
   */
  async getV2Webhooks(
    request?: operations.GetV2WebhooksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetV2WebhooksResponse> {
    return unwrapAsync(webhooksGetV2Webhooks(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a webhook
   *
   * @remarks
   * Create a webhook and associated subscriptions.
   *
   * Required scopes: `webhook:read-write`.
   */
  async postV2Webhooks(
    request: operations.PostV2WebhooksRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2WebhooksResponse> {
    return unwrapAsync(webhooksPostV2Webhooks(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a webhook
   *
   * @remarks
   * Get a single webhook.
   *
   * Required scopes: `webhook:read`.
   */
  async getV2WebhooksWebhookId(
    request: operations.GetV2WebhooksWebhookIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2WebhooksWebhookIdResponse> {
    return unwrapAsync(webhooksGetV2WebhooksWebhookId(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a webhook
   *
   * @remarks
   * Delete a webhook by ID.
   *
   * Required scopes: `webhook:read-write`.
   */
  async deleteV2WebhooksWebhookId(
    request: operations.DeleteV2WebhooksWebhookIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteV2WebhooksWebhookIdResponse> {
    return unwrapAsync(webhooksDeleteV2WebhooksWebhookId(
      this,
      request,
      options,
    ));
  }

  /**
   * Update a webhook
   *
   * @remarks
   * Update a webhook and associated subscriptions.
   *
   * Required scopes: `webhook:read-write`.
   */
  async patchV2WebhooksWebhookId(
    request: operations.PatchV2WebhooksWebhookIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PatchV2WebhooksWebhookIdResponse> {
    return unwrapAsync(webhooksPatchV2WebhooksWebhookId(
      this,
      request,
      options,
    ));
  }
}
