/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceMembersGetV2WorkspaceMembersWorkspaceMemberId } from "../funcs/workspace-members-get-v2-workspace-members-workspace-member-id.js";
import { workspaceMembersGetV2WorkspaceMembers } from "../funcs/workspace-members-get-v2-workspace-members.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class WorkspaceMembers extends ClientSDK {
  /**
   * List workspace members
   *
   * @remarks
   * Lists all workspace members in the workspace.
   *
   * Required scopes: `user_management:read`.
   */
  async getV2WorkspaceMembers(
    options?: RequestOptions,
  ): Promise<operations.GetV2WorkspaceMembersResponse> {
    return unwrapAsync(workspaceMembersGetV2WorkspaceMembers(
      this,
      options,
    ));
  }

  /**
   * Get a workspace member
   *
   * @remarks
   * Gets a single workspace member by ID.
   *
   * Required scopes: `user_management:read`.
   */
  async getV2WorkspaceMembersWorkspaceMemberId(
    request: operations.GetV2WorkspaceMembersWorkspaceMemberIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2WorkspaceMembersWorkspaceMemberIdResponse> {
    return unwrapAsync(workspaceMembersGetV2WorkspaceMembersWorkspaceMemberId(
      this,
      request,
      options,
    ));
  }
}
