workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Attio API:
        inputs:
            - location: https://api.attio.com/openapi/api
        overlays:
            - location: .speakeasy/overlays/enum-fixes-overlay.yaml
            - location: .speakeasy/overlays/single-value-enum-to-const-overlay.yaml
            - location: .speakeasy/overlays/variant-naming-overlay.yaml
            - location: .speakeasy/overlays/speakeasy-modifications-overlay.yaml
        transformations:
            - removeUnused: true
            - cleanup: true
            - format: true
        output: .speakeasy/outputs/attio.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/interfere/api/attio-api
targets:
    attio:
        target: typescript
        source: Attio API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/interfere/api/attio-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
