/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type AssertEntryDataRequest = {
  /**
   * A UUID identifying the record you want to add to the list. The record will become the 'parent' of the created list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the added parent record belongs to.
   */
  parentObject: string;
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  entryValues: { [k: string]: Array<any> };
};

export type AssertEntryRequestBody = {
  data: AssertEntryDataRequest;
};

export type AssertEntryRequest = {
  list: string;
  body: AssertEntryRequestBody;
};

export type AssertEntryId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType17 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType17 = OpenEnum<
  typeof AssertEntryCreatedByActorType17
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor17 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType17 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueTimestamp = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor17;
  /**
   * The attribute type of the value.
   */
  attributeType: "timestamp";
  /**
   * A timestamp value represents a single, universal moment in time using an ISO 8601 formatted string. This means that a timestamp consists of a date, a time (with nanosecond precision), and a time zone. Attio will coerce timestamps which do not provide full nanosecond precision and UTC is assumed if no time zone is provided. For example, "2023", "2023-01", "2023-01-02", "2023-01-02T13:00", "2023-01-02T13:00:00", and "2023-01-02T13:00:00.000000000" will all be coerced to "2023-01-02T13:00:00.000000000Z". Timestamps are always returned in UTC. For example, writing a timestamp value using the string "2023-01-02T13:00:00.000000000+02:00" will result in the value "2023-01-02T11:00:00.000000000Z" being returned. The maximum date is "9999-12-31T23:59:59.999999999Z".
   */
  value: Date;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType16 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType16 = OpenEnum<
  typeof AssertEntryCreatedByActorType16
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor16 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType16 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueText = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor16;
  /**
   * A raw text field. Values are limited to 10MB.
   */
  value: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "text";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType15 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType15 = OpenEnum<
  typeof AssertEntryCreatedByActorType15
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor15 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType15 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueSelect = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor15;
  option: models.SelectOption;
  /**
   * The attribute type of the value.
   */
  attributeType: "select";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType14 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType14 = OpenEnum<
  typeof AssertEntryCreatedByActorType14
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor14 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType14 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueRating = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor14;
  /**
   * A number between 0 and 5 (inclusive) to represent a star rating.
   */
  value: number;
  /**
   * The attribute type of the value.
   */
  attributeType: "rating";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType13 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType13 = OpenEnum<
  typeof AssertEntryCreatedByActorType13
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor13 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType13 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueStatus = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor13;
  status: models.Status;
  /**
   * The attribute type of the value.
   */
  attributeType: "status";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType12 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType12 = OpenEnum<
  typeof AssertEntryCreatedByActorType12
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor12 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType12 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export const AssertEntryCountryCode2 = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Bq: "BQ",
  Kp: "KP",
  Sx: "SX",
  Xk: "XK",
  Ac: "AC",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export type AssertEntryCountryCode2 = OpenEnum<typeof AssertEntryCountryCode2>;

export type AssertEntryEntryValuePhoneNumber = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor12;
  /**
   * The raw, original phone number, as inputted.
   */
  originalPhoneNumber: string;
  /**
   * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
   */
  countryCode: AssertEntryCountryCode2;
  phoneNumber: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "phone-number";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType11 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType11 = OpenEnum<
  typeof AssertEntryCreatedByActorType11
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor11 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType11 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValuePersonalName = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor11;
  /**
   * The first name.
   */
  firstName: string;
  /**
   * The last name.
   */
  lastName: string;
  /**
   * The full name.
   */
  fullName: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "personal-name";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType10 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType10 = OpenEnum<
  typeof AssertEntryCreatedByActorType10
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor10 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType10 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueNumber = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor10;
  /**
   * Numbers are persisted as 64 bit floats.
   */
  value: number;
  /**
   * The attribute type of the value.
   */
  attributeType: "number";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType9 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType9 = OpenEnum<
  typeof AssertEntryCreatedByActorType9
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor9 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType9 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code for the country this location is in.
 */
export const AssertEntryCountryCode1 = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Bq: "BQ",
  Kp: "KP",
  Sx: "SX",
  Xk: "XK",
  Ac: "AC",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code for the country this location is in.
 */
export type AssertEntryCountryCode1 = OpenEnum<typeof AssertEntryCountryCode1>;

export type AssertEntryEntryValueLocation = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor9;
  /**
   * The first line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line1: string | null;
  /**
   * The second line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line2: string | null;
  /**
   * The third line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line3: string | null;
  /**
   * The fourth line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line4: string | null;
  /**
   * The town, neighborhood or area the location is in.
   */
  locality: string | null;
  /**
   * The state, county, province or region that the location is in.
   */
  region: string | null;
  /**
   * The postcode or zip code for the location. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  postcode: string | null;
  /**
   * The ISO 3166-1 alpha-2 country code for the country this location is in.
   */
  countryCode: AssertEntryCountryCode1 | null;
  /**
   * The latitude of the location. Validated by the regular expression `/^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?)$/`. Values are stored with up to 9 decimal places of precision. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  latitude: string | null;
  /**
   * The longitude of the location. Validated by the regular expression `/^[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/`. Values are stored with up to 9 decimal places of precision. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  longitude: string | null;
  /**
   * The attribute type of the value.
   */
  attributeType: "location";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType8 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType8 = OpenEnum<
  typeof AssertEntryCreatedByActorType8
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor8 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType8 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The type of interaction e.g. calendar or email.
 */
export const AssertEntryInteractionType = {
  CalendarEvent: "calendar-event",
  Call: "call",
  ChatThread: "chat-thread",
  Email: "email",
  InPersonMeeting: "in-person-meeting",
  Meeting: "meeting",
} as const;
/**
 * The type of interaction e.g. calendar or email.
 */
export type AssertEntryInteractionType = OpenEnum<
  typeof AssertEntryInteractionType
>;

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryOwnerActorType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryOwnerActorType = OpenEnum<
  typeof AssertEntryOwnerActorType
>;

/**
 * The actor that created this value.
 */
export type AssertEntryOwnerActor = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryOwnerActorType | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueInteraction = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor8;
  /**
   * The type of interaction e.g. calendar or email.
   */
  interactionType: AssertEntryInteractionType;
  /**
   * When the interaction occurred.
   */
  interactedAt: Date;
  /**
   * The actor that created this value.
   */
  ownerActor: AssertEntryOwnerActor;
  /**
   * The attribute type of the value.
   */
  attributeType: "interaction";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType7 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType7 = OpenEnum<
  typeof AssertEntryCreatedByActorType7
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor7 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType7 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueRecordReference = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor7;
  /**
   * A slug identifying the object that the referenced record belongs to.
   */
  targetObject: string;
  /**
   * A UUID to identify the referenced record.
   */
  targetRecordId: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "record-reference";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType6 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType6 = OpenEnum<
  typeof AssertEntryCreatedByActorType6
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor6 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType6 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueEmailAddress = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor6;
  originalEmailAddress: string;
  emailAddress: string;
  emailDomain: string;
  emailRootDomain: string;
  emailLocalSpecifier: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "email-address";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType5 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType5 = OpenEnum<
  typeof AssertEntryCreatedByActorType5
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor5 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType5 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueDomain = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor5;
  domain: string;
  rootDomain: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "domain";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType4 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType4 = OpenEnum<
  typeof AssertEntryCreatedByActorType4
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor4 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType4 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueDate = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor4;
  /**
   * The attribute type of the value.
   */
  attributeType: "date";
  /**
   * A date represents a single calendar year, month and day, independent of timezone. If hours, months, seconds or timezones are provided, they will be trimmed. For example, "2023" and "2023-01" will be coerced into "2023-01-01", and "2023-01-02", "2023-01-02T13:00", "2023-01-02T14:00:00", "2023-01-02T15:00:00.000000000", and "2023-01-02T15:00:00.000000000+02:00" will all be coerced to "2023-01-02". If a timezone is provided that would result in a different calendar date in UTC, the date will be coerced to UTC and then the timezone component will be trimmed. For example, the value "2023-01-02T23:00:00-10:00" will be returned as "2023-01-03". The maximum date is "9999-12-31".
   */
  value: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType3 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType3 = OpenEnum<
  typeof AssertEntryCreatedByActorType3
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor3 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType3 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO4217 currency code representing the currency that the value is stored in.
 */
export const AssertEntryCurrencyCode = {
  Ars: "ARS",
  Aud: "AUD",
  Brl: "BRL",
  Bgn: "BGN",
  Cad: "CAD",
  Clp: "CLP",
  Cny: "CNY",
  Cop: "COP",
  Czk: "CZK",
  Dkk: "DKK",
  Egp: "EGP",
  Eur: "EUR",
  Fjd: "FJD",
  Ghs: "GHS",
  Hkd: "HKD",
  Huf: "HUF",
  Isk: "ISK",
  Inr: "INR",
  Idr: "IDR",
  Ils: "ILS",
  Jpy: "JPY",
  Kes: "KES",
  Krw: "KRW",
  Myr: "MYR",
  Mxn: "MXN",
  Ntd: "NTD",
  Nzd: "NZD",
  Ngn: "NGN",
  Nok: "NOK",
  Omr: "OMR",
  Xpf: "XPF",
  Pen: "PEN",
  Php: "PHP",
  Pln: "PLN",
  Gbp: "GBP",
  Qar: "QAR",
  Rwf: "RWF",
  Sar: "SAR",
  Sgd: "SGD",
  Zar: "ZAR",
  Sek: "SEK",
  Chf: "CHF",
  Thb: "THB",
  Try: "TRY",
  Aed: "AED",
  Uyu: "UYU",
  Usd: "USD",
} as const;
/**
 * The ISO4217 currency code representing the currency that the value is stored in.
 */
export type AssertEntryCurrencyCode = OpenEnum<typeof AssertEntryCurrencyCode>;

export type AssertEntryEntryValueCurrency = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor3;
  /**
   * A numerical representation of the currency value. A decimal with a max of 4 decimal places.
   */
  currencyValue: number;
  /**
   * The ISO4217 currency code representing the currency that the value is stored in.
   */
  currencyCode?: AssertEntryCurrencyCode | null | undefined;
  /**
   * The attribute type of the value.
   */
  attributeType: "currency";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType2 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType2 = OpenEnum<
  typeof AssertEntryCreatedByActorType2
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor2 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType2 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type AssertEntryEntryValueCheckbox = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor2;
  /**
   * A boolean representing whether the checkbox is checked or not. The string values 'true' and 'false' are also accepted.
   */
  value: boolean;
  /**
   * The attribute type of the value.
   */
  attributeType: "checkbox";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryCreatedByActorType1 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryCreatedByActorType1 = OpenEnum<
  typeof AssertEntryCreatedByActorType1
>;

/**
 * The actor that created this value.
 */
export type AssertEntryCreatedByActor1 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AssertEntryCreatedByActorType1 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
 */
export const AssertEntryReferencedActorType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
 */
export type AssertEntryReferencedActorType = OpenEnum<
  typeof AssertEntryReferencedActorType
>;

export type AssertEntryEntryValueActorReference = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: AssertEntryCreatedByActor1;
  /**
   * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
   */
  referencedActorType: AssertEntryReferencedActorType;
  /**
   * The ID of the referenced actor.
   */
  referencedActorId: string | null;
  /**
   * The attribute type of the value.
   */
  attributeType: "actor-reference";
};

export type AssertEntryEntryValueUnion =
  | AssertEntryEntryValueActorReference
  | AssertEntryEntryValueCheckbox
  | AssertEntryEntryValueCurrency
  | AssertEntryEntryValueDate
  | AssertEntryEntryValueDomain
  | AssertEntryEntryValueEmailAddress
  | AssertEntryEntryValueRecordReference
  | AssertEntryEntryValueInteraction
  | AssertEntryEntryValueLocation
  | AssertEntryEntryValueNumber
  | AssertEntryEntryValuePersonalName
  | AssertEntryEntryValuePhoneNumber
  | AssertEntryEntryValueStatus
  | AssertEntryEntryValueRating
  | AssertEntryEntryValueSelect
  | AssertEntryEntryValueText
  | AssertEntryEntryValueTimestamp
  | discriminatedUnionTypes.Unknown<"attributeType">;

export type AssertEntryDataResponse = {
  id: AssertEntryId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: {
    [k: string]: Array<
      | AssertEntryEntryValueActorReference
      | AssertEntryEntryValueCheckbox
      | AssertEntryEntryValueCurrency
      | AssertEntryEntryValueDate
      | AssertEntryEntryValueDomain
      | AssertEntryEntryValueEmailAddress
      | AssertEntryEntryValueRecordReference
      | AssertEntryEntryValueInteraction
      | AssertEntryEntryValueLocation
      | AssertEntryEntryValueNumber
      | AssertEntryEntryValuePersonalName
      | AssertEntryEntryValuePhoneNumber
      | AssertEntryEntryValueStatus
      | AssertEntryEntryValueRating
      | AssertEntryEntryValueSelect
      | AssertEntryEntryValueText
      | AssertEntryEntryValueTimestamp
      | discriminatedUnionTypes.Unknown<"attributeType">
    >;
  };
};

/**
 * Success
 */
export type AssertEntryResponse = {
  data: AssertEntryDataResponse;
};

/** @internal */
export type AssertEntryDataRequest$Outbound = {
  parent_record_id: string;
  parent_object: string;
  entry_values: { [k: string]: Array<any> };
};

/** @internal */
export const AssertEntryDataRequest$outboundSchema: z.ZodMiniType<
  AssertEntryDataRequest$Outbound,
  AssertEntryDataRequest
> = z.pipe(
  z.object({
    parentRecordId: z.string(),
    parentObject: z.string(),
    entryValues: z.record(z.string(), z.array(z.any())),
  }),
  z.transform((v) => {
    return remap$(v, {
      parentRecordId: "parent_record_id",
      parentObject: "parent_object",
      entryValues: "entry_values",
    });
  }),
);

export function assertEntryDataRequestToJSON(
  assertEntryDataRequest: AssertEntryDataRequest,
): string {
  return JSON.stringify(
    AssertEntryDataRequest$outboundSchema.parse(assertEntryDataRequest),
  );
}

/** @internal */
export type AssertEntryRequestBody$Outbound = {
  data: AssertEntryDataRequest$Outbound;
};

/** @internal */
export const AssertEntryRequestBody$outboundSchema: z.ZodMiniType<
  AssertEntryRequestBody$Outbound,
  AssertEntryRequestBody
> = z.object({
  data: z.lazy(() => AssertEntryDataRequest$outboundSchema),
});

export function assertEntryRequestBodyToJSON(
  assertEntryRequestBody: AssertEntryRequestBody,
): string {
  return JSON.stringify(
    AssertEntryRequestBody$outboundSchema.parse(assertEntryRequestBody),
  );
}

/** @internal */
export type AssertEntryRequest$Outbound = {
  list: string;
  body: AssertEntryRequestBody$Outbound;
};

/** @internal */
export const AssertEntryRequest$outboundSchema: z.ZodMiniType<
  AssertEntryRequest$Outbound,
  AssertEntryRequest
> = z.object({
  list: z.string(),
  body: z.lazy(() => AssertEntryRequestBody$outboundSchema),
});

export function assertEntryRequestToJSON(
  assertEntryRequest: AssertEntryRequest,
): string {
  return JSON.stringify(
    AssertEntryRequest$outboundSchema.parse(assertEntryRequest),
  );
}

/** @internal */
export const AssertEntryId$inboundSchema: z.ZodMiniType<
  AssertEntryId,
  unknown
> = z.pipe(
  z.object({
    workspace_id: types.string(),
    list_id: types.string(),
    entry_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "list_id": "listId",
      "entry_id": "entryId",
    });
  }),
);

export function assertEntryIdFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryId' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType17$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType17,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType17);

/** @internal */
export const AssertEntryCreatedByActor17$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor17,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType17$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor17FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor17, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor17$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor17' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueTimestamp$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueTimestamp,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor17$inboundSchema),
    attribute_type: types.literal("timestamp"),
    value: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueTimestampFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueTimestamp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueTimestamp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueTimestamp' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType16$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType16,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType16);

/** @internal */
export const AssertEntryCreatedByActor16$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor16,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType16$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor16FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor16, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor16$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor16' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueText$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueText,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor16$inboundSchema),
    value: types.string(),
    attribute_type: types.literal("text"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueTextFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueText' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType15$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType15,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType15);

/** @internal */
export const AssertEntryCreatedByActor15$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor15,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType15$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor15FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor15, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor15$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor15' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueSelect$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueSelect,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor15$inboundSchema),
    option: models.SelectOption$inboundSchema,
    attribute_type: types.literal("select"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueSelectFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueSelect, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueSelect$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueSelect' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType14$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType14,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType14);

/** @internal */
export const AssertEntryCreatedByActor14$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor14,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType14$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor14FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor14, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor14$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor14' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueRating$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueRating,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor14$inboundSchema),
    value: types.number(),
    attribute_type: types.literal("rating"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueRatingFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueRating' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType13$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType13,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType13);

/** @internal */
export const AssertEntryCreatedByActor13$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor13,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType13$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor13FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor13, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor13$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor13' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueStatus$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueStatus,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor13$inboundSchema),
    status: models.Status$inboundSchema,
    attribute_type: types.literal("status"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueStatusFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueStatus' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType12$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType12,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType12);

/** @internal */
export const AssertEntryCreatedByActor12$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor12,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType12$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor12FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor12, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor12$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor12' from JSON`,
  );
}

/** @internal */
export const AssertEntryCountryCode2$inboundSchema: z.ZodMiniType<
  AssertEntryCountryCode2,
  unknown
> = openEnums.inboundSchema(AssertEntryCountryCode2);

/** @internal */
export const AssertEntryEntryValuePhoneNumber$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValuePhoneNumber,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor12$inboundSchema),
    original_phone_number: types.string(),
    country_code: AssertEntryCountryCode2$inboundSchema,
    phone_number: types.string(),
    attribute_type: types.literal("phone-number"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "original_phone_number": "originalPhoneNumber",
      "country_code": "countryCode",
      "phone_number": "phoneNumber",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValuePhoneNumberFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValuePhoneNumber, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValuePhoneNumber$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValuePhoneNumber' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType11$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType11,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType11);

/** @internal */
export const AssertEntryCreatedByActor11$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor11,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType11$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor11FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor11, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor11$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor11' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValuePersonalName$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValuePersonalName,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor11$inboundSchema),
    first_name: types.string(),
    last_name: types.string(),
    full_name: types.string(),
    attribute_type: types.literal("personal-name"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "first_name": "firstName",
      "last_name": "lastName",
      "full_name": "fullName",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValuePersonalNameFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValuePersonalName, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValuePersonalName$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValuePersonalName' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType10$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType10,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType10);

/** @internal */
export const AssertEntryCreatedByActor10$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor10,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType10$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor10FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor10, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor10$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor10' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueNumber$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueNumber,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor10$inboundSchema),
    value: types.number(),
    attribute_type: types.literal("number"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueNumberFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueNumber, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueNumber$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueNumber' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType9$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType9,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType9);

/** @internal */
export const AssertEntryCreatedByActor9$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor9,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType9$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor9FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor9, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor9$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor9' from JSON`,
  );
}

/** @internal */
export const AssertEntryCountryCode1$inboundSchema: z.ZodMiniType<
  AssertEntryCountryCode1,
  unknown
> = openEnums.inboundSchema(AssertEntryCountryCode1);

/** @internal */
export const AssertEntryEntryValueLocation$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueLocation,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor9$inboundSchema),
    line_1: types.nullable(types.string()),
    line_2: types.nullable(types.string()),
    line_3: types.nullable(types.string()),
    line_4: types.nullable(types.string()),
    locality: types.nullable(types.string()),
    region: types.nullable(types.string()),
    postcode: types.nullable(types.string()),
    country_code: types.nullable(AssertEntryCountryCode1$inboundSchema),
    latitude: types.nullable(types.string()),
    longitude: types.nullable(types.string()),
    attribute_type: types.literal("location"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "line_1": "line1",
      "line_2": "line2",
      "line_3": "line3",
      "line_4": "line4",
      "country_code": "countryCode",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueLocationFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueLocation' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType8$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType8,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType8);

/** @internal */
export const AssertEntryCreatedByActor8$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor8,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType8$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor8FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor8, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor8$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor8' from JSON`,
  );
}

/** @internal */
export const AssertEntryInteractionType$inboundSchema: z.ZodMiniType<
  AssertEntryInteractionType,
  unknown
> = openEnums.inboundSchema(AssertEntryInteractionType);

/** @internal */
export const AssertEntryOwnerActorType$inboundSchema: z.ZodMiniType<
  AssertEntryOwnerActorType,
  unknown
> = openEnums.inboundSchema(AssertEntryOwnerActorType);

/** @internal */
export const AssertEntryOwnerActor$inboundSchema: z.ZodMiniType<
  AssertEntryOwnerActor,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryOwnerActorType$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryOwnerActorFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryOwnerActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryOwnerActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryOwnerActor' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueInteraction$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueInteraction,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor8$inboundSchema),
    interaction_type: AssertEntryInteractionType$inboundSchema,
    interacted_at: types.date(),
    owner_actor: z.lazy(() => AssertEntryOwnerActor$inboundSchema),
    attribute_type: types.literal("interaction"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "interaction_type": "interactionType",
      "interacted_at": "interactedAt",
      "owner_actor": "ownerActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueInteractionFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueInteraction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueInteraction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueInteraction' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType7$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType7,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType7);

/** @internal */
export const AssertEntryCreatedByActor7$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor7,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType7$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor7FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor7' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueRecordReference$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueRecordReference,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor7$inboundSchema),
    target_object: types.string(),
    target_record_id: types.string(),
    attribute_type: types.literal("record-reference"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "target_object": "targetObject",
      "target_record_id": "targetRecordId",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueRecordReferenceFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueRecordReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AssertEntryEntryValueRecordReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueRecordReference' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType6$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType6,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType6);

/** @internal */
export const AssertEntryCreatedByActor6$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor6,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType6$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor6FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor6, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor6$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor6' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueEmailAddress$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueEmailAddress,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor6$inboundSchema),
    original_email_address: types.string(),
    email_address: types.string(),
    email_domain: types.string(),
    email_root_domain: types.string(),
    email_local_specifier: types.string(),
    attribute_type: types.literal("email-address"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "original_email_address": "originalEmailAddress",
      "email_address": "emailAddress",
      "email_domain": "emailDomain",
      "email_root_domain": "emailRootDomain",
      "email_local_specifier": "emailLocalSpecifier",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueEmailAddressFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueEmailAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueEmailAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueEmailAddress' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType5$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType5,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType5);

/** @internal */
export const AssertEntryCreatedByActor5$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor5,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType5$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor5FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor5' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueDomain$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueDomain,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor5$inboundSchema),
    domain: types.string(),
    root_domain: types.string(),
    attribute_type: types.literal("domain"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "root_domain": "rootDomain",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueDomainFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueDomain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueDomain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueDomain' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType4$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType4,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType4);

/** @internal */
export const AssertEntryCreatedByActor4$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor4,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType4$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor4FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor4' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueDate$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueDate,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor4$inboundSchema),
    attribute_type: types.literal("date"),
    value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueDateFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueDate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueDate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueDate' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType3$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType3,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType3);

/** @internal */
export const AssertEntryCreatedByActor3$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor3,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType3$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor3FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor3' from JSON`,
  );
}

/** @internal */
export const AssertEntryCurrencyCode$inboundSchema: z.ZodMiniType<
  AssertEntryCurrencyCode,
  unknown
> = openEnums.inboundSchema(AssertEntryCurrencyCode);

/** @internal */
export const AssertEntryEntryValueCurrency$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueCurrency,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor3$inboundSchema),
    currency_value: types.number(),
    currency_code: z.optional(
      z.nullable(AssertEntryCurrencyCode$inboundSchema),
    ),
    attribute_type: types.literal("currency"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "currency_value": "currencyValue",
      "currency_code": "currencyCode",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueCurrency' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType2$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType2,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType2);

/** @internal */
export const AssertEntryCreatedByActor2$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor2,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType2$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor2FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor2' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueCheckbox$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueCheckbox,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor2$inboundSchema),
    value: types.boolean(),
    attribute_type: types.literal("checkbox"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueCheckboxFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueCheckbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueCheckbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueCheckbox' from JSON`,
  );
}

/** @internal */
export const AssertEntryCreatedByActorType1$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActorType1,
  unknown
> = openEnums.inboundSchema(AssertEntryCreatedByActorType1);

/** @internal */
export const AssertEntryCreatedByActor1$inboundSchema: z.ZodMiniType<
  AssertEntryCreatedByActor1,
  unknown
> = z.object({
  type: z.optional(z.nullable(AssertEntryCreatedByActorType1$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function assertEntryCreatedByActor1FromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryCreatedByActor1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryCreatedByActor1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryCreatedByActor1' from JSON`,
  );
}

/** @internal */
export const AssertEntryReferencedActorType$inboundSchema: z.ZodMiniType<
  AssertEntryReferencedActorType,
  unknown
> = openEnums.inboundSchema(AssertEntryReferencedActorType);

/** @internal */
export const AssertEntryEntryValueActorReference$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueActorReference,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => AssertEntryCreatedByActor1$inboundSchema),
    referenced_actor_type: AssertEntryReferencedActorType$inboundSchema,
    referenced_actor_id: types.nullable(types.string()),
    attribute_type: types.literal("actor-reference"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "referenced_actor_type": "referencedActorType",
      "referenced_actor_id": "referencedActorId",
      "attribute_type": "attributeType",
    });
  }),
);

export function assertEntryEntryValueActorReferenceFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueActorReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AssertEntryEntryValueActorReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueActorReference' from JSON`,
  );
}

/** @internal */
export const AssertEntryEntryValueUnion$inboundSchema: z.ZodMiniType<
  AssertEntryEntryValueUnion,
  unknown
> = discriminatedUnion("attribute_type", {
  ["actor-reference"]: z.lazy(() =>
    AssertEntryEntryValueActorReference$inboundSchema
  ),
  checkbox: z.lazy(() => AssertEntryEntryValueCheckbox$inboundSchema),
  currency: z.lazy(() => AssertEntryEntryValueCurrency$inboundSchema),
  date: z.lazy(() => AssertEntryEntryValueDate$inboundSchema),
  domain: z.lazy(() => AssertEntryEntryValueDomain$inboundSchema),
  ["email-address"]: z.lazy(() =>
    AssertEntryEntryValueEmailAddress$inboundSchema
  ),
  ["record-reference"]: z.lazy(() =>
    AssertEntryEntryValueRecordReference$inboundSchema
  ),
  interaction: z.lazy(() => AssertEntryEntryValueInteraction$inboundSchema),
  location: z.lazy(() => AssertEntryEntryValueLocation$inboundSchema),
  number: z.lazy(() => AssertEntryEntryValueNumber$inboundSchema),
  ["personal-name"]: z.lazy(() =>
    AssertEntryEntryValuePersonalName$inboundSchema
  ),
  ["phone-number"]: z.lazy(() =>
    AssertEntryEntryValuePhoneNumber$inboundSchema
  ),
  status: z.lazy(() => AssertEntryEntryValueStatus$inboundSchema),
  rating: z.lazy(() => AssertEntryEntryValueRating$inboundSchema),
  select: z.lazy(() => AssertEntryEntryValueSelect$inboundSchema),
  text: z.lazy(() => AssertEntryEntryValueText$inboundSchema),
  timestamp: z.lazy(() => AssertEntryEntryValueTimestamp$inboundSchema),
}, { outputPropertyName: "attributeType" });

export function assertEntryEntryValueUnionFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryEntryValueUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryEntryValueUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryEntryValueUnion' from JSON`,
  );
}

/** @internal */
export const AssertEntryDataResponse$inboundSchema: z.ZodMiniType<
  AssertEntryDataResponse,
  unknown
> = z.pipe(
  z.object({
    id: z.lazy(() => AssertEntryId$inboundSchema),
    parent_record_id: types.string(),
    parent_object: types.string(),
    created_at: types.string(),
    entry_values: z.record(
      z.string(),
      z.array(discriminatedUnion("attribute_type", {
        ["actor-reference"]: z.lazy(() =>
          AssertEntryEntryValueActorReference$inboundSchema
        ),
        checkbox: z.lazy(() => AssertEntryEntryValueCheckbox$inboundSchema),
        currency: z.lazy(() => AssertEntryEntryValueCurrency$inboundSchema),
        date: z.lazy(() => AssertEntryEntryValueDate$inboundSchema),
        domain: z.lazy(() => AssertEntryEntryValueDomain$inboundSchema),
        ["email-address"]: z.lazy(() =>
          AssertEntryEntryValueEmailAddress$inboundSchema
        ),
        ["record-reference"]: z.lazy(() =>
          AssertEntryEntryValueRecordReference$inboundSchema
        ),
        interaction: z.lazy(() =>
          AssertEntryEntryValueInteraction$inboundSchema
        ),
        location: z.lazy(() => AssertEntryEntryValueLocation$inboundSchema),
        number: z.lazy(() => AssertEntryEntryValueNumber$inboundSchema),
        ["personal-name"]: z.lazy(() =>
          AssertEntryEntryValuePersonalName$inboundSchema
        ),
        ["phone-number"]: z.lazy(() =>
          AssertEntryEntryValuePhoneNumber$inboundSchema
        ),
        status: z.lazy(() => AssertEntryEntryValueStatus$inboundSchema),
        rating: z.lazy(() => AssertEntryEntryValueRating$inboundSchema),
        select: z.lazy(() => AssertEntryEntryValueSelect$inboundSchema),
        text: z.lazy(() => AssertEntryEntryValueText$inboundSchema),
        timestamp: z.lazy(() => AssertEntryEntryValueTimestamp$inboundSchema),
      }, { outputPropertyName: "attributeType" })),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "parent_record_id": "parentRecordId",
      "parent_object": "parentObject",
      "created_at": "createdAt",
      "entry_values": "entryValues",
    });
  }),
);

export function assertEntryDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryDataResponse' from JSON`,
  );
}

/** @internal */
export const AssertEntryResponse$inboundSchema: z.ZodMiniType<
  AssertEntryResponse,
  unknown
> = z.object({
  data: z.lazy(() => AssertEntryDataResponse$inboundSchema),
});

export function assertEntryResponseFromJSON(
  jsonString: string,
): SafeParseResult<AssertEntryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AssertEntryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AssertEntryResponse' from JSON`,
  );
}
