/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * The format of the task content to be created. Rich text formatting, links and @references are not supported.
 */
export const CreateTaskFormat = {
  Plaintext: "plaintext",
} as const;
/**
 * The format of the task content to be created. Rich text formatting, links and @references are not supported.
 */
export type CreateTaskFormat = ClosedEnum<typeof CreateTaskFormat>;

export type CreateTaskSlugOrIdOfMatchingAttribute5 = {
  /**
   * A raw text field. Values are limited to 10MB.
   */
  value?: string | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export const CreateTaskCountryCode = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Bq: "BQ",
  Kp: "KP",
  Sx: "SX",
  Xk: "XK",
  Ac: "AC",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export type CreateTaskCountryCode = ClosedEnum<typeof CreateTaskCountryCode>;

export type CreateTaskSlugOrIdOfMatchingAttribute4 = {
  /**
   * The raw, original phone number, as inputted.
   */
  originalPhoneNumber?: string | undefined;
  /**
   * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
   */
  countryCode?: CreateTaskCountryCode | null | undefined;
};

export type CreateTaskSlugOrIdOfMatchingAttribute3 = {
  /**
   * Numbers are persisted as 64 bit floats.
   */
  value?: number | undefined;
};

export type CreateTaskSlugOrIdOfMatchingAttribute2 = {
  /**
   * An email address string
   */
  emailAddress?: string | undefined;
};

export type CreateTaskSlugOrIdOfMatchingAttribute1 = {
  /**
   * The full domain of the website.
   */
  domain?: string | undefined;
};

export type CreateTaskSlugOrIdOfMatchingAttributeUnion =
  | CreateTaskSlugOrIdOfMatchingAttribute1
  | CreateTaskSlugOrIdOfMatchingAttribute2
  | CreateTaskSlugOrIdOfMatchingAttribute3
  | CreateTaskSlugOrIdOfMatchingAttribute4
  | CreateTaskSlugOrIdOfMatchingAttribute5;

export type CreateTaskLinkedRecord2 = {
  /**
   * A UUID or slug to identify the object that the referenced record belongs to.
   */
  targetObject: string;
  /**
   * In addition to referencing records directly by record ID, you may also reference by a matching attribute of your choice. For example, if you want to add a reference to the person record with email "alice@website.com", you should pass a value with `target_object` set to `"people"` and `email_addresses` set to `[{email_address:"alice@website.com"}]`. The key should be the slug or ID of the matching attribute you would like to use and the value should be an array containing a single value of the appropriate attribute type (as specified below). Matching on multiple values is not currently supported. Matching attributes must be unique. This process is similar to how you use the `matching_attribute` query param in Attio's [assert endpoints](/rest-api/endpoint-reference/records/assert-a-record).
   */
  slugOrIdOfMatchingAttribute: Array<
    | CreateTaskSlugOrIdOfMatchingAttribute1
    | CreateTaskSlugOrIdOfMatchingAttribute2
    | CreateTaskSlugOrIdOfMatchingAttribute3
    | CreateTaskSlugOrIdOfMatchingAttribute4
    | CreateTaskSlugOrIdOfMatchingAttribute5
  >;
};

export type CreateTaskLinkedRecord1 = {
  /**
   * The ID or slug of the parent object the tasks refers to. This can reference both standard and custom objects.`
   */
  targetObject: string;
  /**
   * The ID of the parent record the task refers to.
   */
  targetRecordId: string;
};

export type CreateTaskLinkedRecordUnion =
  | CreateTaskLinkedRecord1
  | CreateTaskLinkedRecord2;

export type CreateTaskAssignee = {
  /**
   * Workspace member actors can be referenced by email address as well as actor ID.
   */
  workspaceMemberEmailAddress: string;
};

/**
 * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
 */
export const CreateTaskReferencedActorType = {
  WorkspaceMember: "workspace-member",
} as const;
/**
 * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
 */
export type CreateTaskReferencedActorType = ClosedEnum<
  typeof CreateTaskReferencedActorType
>;

export type CreateTaskAssigneeWorkspaceMember = {
  /**
   * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
   */
  referencedActorType: CreateTaskReferencedActorType;
  /**
   * The ID of the actor assigned to this task.
   */
  referencedActorId: string;
};

export type CreateTaskAssigneeUnion =
  | CreateTaskAssigneeWorkspaceMember
  | CreateTaskAssignee;

export type CreateTaskData = {
  /**
   * The text content of the task, in the format specified by the `format` property. A max length of 2000 characters is enforced.
   */
  content: string;
  /**
   * The format of the task content to be created. Rich text formatting, links and @references are not supported.
   */
  format: CreateTaskFormat;
  /**
   * The deadline of the task, in ISO 8601 format.
   */
  deadlineAt: string | null;
  /**
   * Whether the task has been completed.
   */
  isCompleted: boolean;
  /**
   * Records linked to the task. Creating record links within task content text is not possible via the API at present.
   */
  linkedRecords: Array<CreateTaskLinkedRecord1 | CreateTaskLinkedRecord2>;
  /**
   * Workspace members assigned to this task.
   */
  assignees: Array<CreateTaskAssigneeWorkspaceMember | CreateTaskAssignee>;
};

export type CreateTaskRequest = {
  data: CreateTaskData;
};

export const CreateTaskNotFoundStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type CreateTaskNotFoundStatusCode = ClosedEnum<
  typeof CreateTaskNotFoundStatusCode
>;

export const CreateTaskNotFoundType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type CreateTaskNotFoundType = ClosedEnum<typeof CreateTaskNotFoundType>;

export const CreateTaskNotFoundCode = {
  NotFound: "not_found",
} as const;
export type CreateTaskNotFoundCode = ClosedEnum<typeof CreateTaskNotFoundCode>;

export const CreateTaskBadRequestStatusCode = {
  FourHundred: 400,
} as const;
export type CreateTaskBadRequestStatusCode = ClosedEnum<
  typeof CreateTaskBadRequestStatusCode
>;

export const CreateTaskBadRequestType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type CreateTaskBadRequestType = ClosedEnum<
  typeof CreateTaskBadRequestType
>;

export const CreateTaskCodeValidationType = {
  ValidationType: "validation_type",
} as const;
export type CreateTaskCodeValidationType = ClosedEnum<
  typeof CreateTaskCodeValidationType
>;

/**
 * Success
 */
export type CreateTaskResponse = {
  data: models.Task;
};

/** @internal */
export const CreateTaskFormat$outboundSchema: z.ZodMiniEnum<
  typeof CreateTaskFormat
> = z.enum(CreateTaskFormat);

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttribute5$Outbound = {
  value?: string | undefined;
};

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttribute5$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttribute5$Outbound,
    CreateTaskSlugOrIdOfMatchingAttribute5
  > = z.object({
    value: z.optional(z.string()),
  });

export function createTaskSlugOrIdOfMatchingAttribute5ToJSON(
  createTaskSlugOrIdOfMatchingAttribute5:
    CreateTaskSlugOrIdOfMatchingAttribute5,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttribute5$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttribute5,
    ),
  );
}

/** @internal */
export const CreateTaskCountryCode$outboundSchema: z.ZodMiniEnum<
  typeof CreateTaskCountryCode
> = z.enum(CreateTaskCountryCode);

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttribute4$Outbound = {
  original_phone_number?: string | undefined;
  country_code?: string | null | undefined;
};

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttribute4$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttribute4$Outbound,
    CreateTaskSlugOrIdOfMatchingAttribute4
  > = z.pipe(
    z.object({
      originalPhoneNumber: z.optional(z.string()),
      countryCode: z.optional(z.nullable(CreateTaskCountryCode$outboundSchema)),
    }),
    z.transform((v) => {
      return remap$(v, {
        originalPhoneNumber: "original_phone_number",
        countryCode: "country_code",
      });
    }),
  );

export function createTaskSlugOrIdOfMatchingAttribute4ToJSON(
  createTaskSlugOrIdOfMatchingAttribute4:
    CreateTaskSlugOrIdOfMatchingAttribute4,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttribute4$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttribute4,
    ),
  );
}

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttribute3$Outbound = {
  value?: number | undefined;
};

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttribute3$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttribute3$Outbound,
    CreateTaskSlugOrIdOfMatchingAttribute3
  > = z.object({
    value: z.optional(z.number()),
  });

export function createTaskSlugOrIdOfMatchingAttribute3ToJSON(
  createTaskSlugOrIdOfMatchingAttribute3:
    CreateTaskSlugOrIdOfMatchingAttribute3,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttribute3$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttribute3,
    ),
  );
}

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttribute2$Outbound = {
  email_address?: string | undefined;
};

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttribute2$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttribute2$Outbound,
    CreateTaskSlugOrIdOfMatchingAttribute2
  > = z.pipe(
    z.object({
      emailAddress: z.optional(z.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        emailAddress: "email_address",
      });
    }),
  );

export function createTaskSlugOrIdOfMatchingAttribute2ToJSON(
  createTaskSlugOrIdOfMatchingAttribute2:
    CreateTaskSlugOrIdOfMatchingAttribute2,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttribute2$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttribute2,
    ),
  );
}

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttribute1$Outbound = {
  domain?: string | undefined;
};

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttribute1$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttribute1$Outbound,
    CreateTaskSlugOrIdOfMatchingAttribute1
  > = z.object({
    domain: z.optional(z.string()),
  });

export function createTaskSlugOrIdOfMatchingAttribute1ToJSON(
  createTaskSlugOrIdOfMatchingAttribute1:
    CreateTaskSlugOrIdOfMatchingAttribute1,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttribute1$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttribute1,
    ),
  );
}

/** @internal */
export type CreateTaskSlugOrIdOfMatchingAttributeUnion$Outbound =
  | CreateTaskSlugOrIdOfMatchingAttribute1$Outbound
  | CreateTaskSlugOrIdOfMatchingAttribute2$Outbound
  | CreateTaskSlugOrIdOfMatchingAttribute3$Outbound
  | CreateTaskSlugOrIdOfMatchingAttribute4$Outbound
  | CreateTaskSlugOrIdOfMatchingAttribute5$Outbound;

/** @internal */
export const CreateTaskSlugOrIdOfMatchingAttributeUnion$outboundSchema:
  z.ZodMiniType<
    CreateTaskSlugOrIdOfMatchingAttributeUnion$Outbound,
    CreateTaskSlugOrIdOfMatchingAttributeUnion
  > = smartUnion([
    z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute1$outboundSchema),
    z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute2$outboundSchema),
    z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute3$outboundSchema),
    z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute4$outboundSchema),
    z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute5$outboundSchema),
  ]);

export function createTaskSlugOrIdOfMatchingAttributeUnionToJSON(
  createTaskSlugOrIdOfMatchingAttributeUnion:
    CreateTaskSlugOrIdOfMatchingAttributeUnion,
): string {
  return JSON.stringify(
    CreateTaskSlugOrIdOfMatchingAttributeUnion$outboundSchema.parse(
      createTaskSlugOrIdOfMatchingAttributeUnion,
    ),
  );
}

/** @internal */
export type CreateTaskLinkedRecord2$Outbound = {
  target_object: string;
  "[slug_or_id_of_matching_attribute]": Array<
    | CreateTaskSlugOrIdOfMatchingAttribute1$Outbound
    | CreateTaskSlugOrIdOfMatchingAttribute2$Outbound
    | CreateTaskSlugOrIdOfMatchingAttribute3$Outbound
    | CreateTaskSlugOrIdOfMatchingAttribute4$Outbound
    | CreateTaskSlugOrIdOfMatchingAttribute5$Outbound
  >;
};

/** @internal */
export const CreateTaskLinkedRecord2$outboundSchema: z.ZodMiniType<
  CreateTaskLinkedRecord2$Outbound,
  CreateTaskLinkedRecord2
> = z.pipe(
  z.object({
    targetObject: z.string(),
    slugOrIdOfMatchingAttribute: z.array(smartUnion([
      z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute1$outboundSchema),
      z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute2$outboundSchema),
      z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute3$outboundSchema),
      z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute4$outboundSchema),
      z.lazy(() => CreateTaskSlugOrIdOfMatchingAttribute5$outboundSchema),
    ])),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetObject: "target_object",
      slugOrIdOfMatchingAttribute: "[slug_or_id_of_matching_attribute]",
    });
  }),
);

export function createTaskLinkedRecord2ToJSON(
  createTaskLinkedRecord2: CreateTaskLinkedRecord2,
): string {
  return JSON.stringify(
    CreateTaskLinkedRecord2$outboundSchema.parse(createTaskLinkedRecord2),
  );
}

/** @internal */
export type CreateTaskLinkedRecord1$Outbound = {
  target_object: string;
  target_record_id: string;
};

/** @internal */
export const CreateTaskLinkedRecord1$outboundSchema: z.ZodMiniType<
  CreateTaskLinkedRecord1$Outbound,
  CreateTaskLinkedRecord1
> = z.pipe(
  z.object({
    targetObject: z.string(),
    targetRecordId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetObject: "target_object",
      targetRecordId: "target_record_id",
    });
  }),
);

export function createTaskLinkedRecord1ToJSON(
  createTaskLinkedRecord1: CreateTaskLinkedRecord1,
): string {
  return JSON.stringify(
    CreateTaskLinkedRecord1$outboundSchema.parse(createTaskLinkedRecord1),
  );
}

/** @internal */
export type CreateTaskLinkedRecordUnion$Outbound =
  | CreateTaskLinkedRecord1$Outbound
  | CreateTaskLinkedRecord2$Outbound;

/** @internal */
export const CreateTaskLinkedRecordUnion$outboundSchema: z.ZodMiniType<
  CreateTaskLinkedRecordUnion$Outbound,
  CreateTaskLinkedRecordUnion
> = smartUnion([
  z.lazy(() => CreateTaskLinkedRecord1$outboundSchema),
  z.lazy(() => CreateTaskLinkedRecord2$outboundSchema),
]);

export function createTaskLinkedRecordUnionToJSON(
  createTaskLinkedRecordUnion: CreateTaskLinkedRecordUnion,
): string {
  return JSON.stringify(
    CreateTaskLinkedRecordUnion$outboundSchema.parse(
      createTaskLinkedRecordUnion,
    ),
  );
}

/** @internal */
export type CreateTaskAssignee$Outbound = {
  workspace_member_email_address: string;
};

/** @internal */
export const CreateTaskAssignee$outboundSchema: z.ZodMiniType<
  CreateTaskAssignee$Outbound,
  CreateTaskAssignee
> = z.pipe(
  z.object({
    workspaceMemberEmailAddress: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      workspaceMemberEmailAddress: "workspace_member_email_address",
    });
  }),
);

export function createTaskAssigneeToJSON(
  createTaskAssignee: CreateTaskAssignee,
): string {
  return JSON.stringify(
    CreateTaskAssignee$outboundSchema.parse(createTaskAssignee),
  );
}

/** @internal */
export const CreateTaskReferencedActorType$outboundSchema: z.ZodMiniEnum<
  typeof CreateTaskReferencedActorType
> = z.enum(CreateTaskReferencedActorType);

/** @internal */
export type CreateTaskAssigneeWorkspaceMember$Outbound = {
  referenced_actor_type: string;
  referenced_actor_id: string;
};

/** @internal */
export const CreateTaskAssigneeWorkspaceMember$outboundSchema: z.ZodMiniType<
  CreateTaskAssigneeWorkspaceMember$Outbound,
  CreateTaskAssigneeWorkspaceMember
> = z.pipe(
  z.object({
    referencedActorType: CreateTaskReferencedActorType$outboundSchema,
    referencedActorId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      referencedActorType: "referenced_actor_type",
      referencedActorId: "referenced_actor_id",
    });
  }),
);

export function createTaskAssigneeWorkspaceMemberToJSON(
  createTaskAssigneeWorkspaceMember: CreateTaskAssigneeWorkspaceMember,
): string {
  return JSON.stringify(
    CreateTaskAssigneeWorkspaceMember$outboundSchema.parse(
      createTaskAssigneeWorkspaceMember,
    ),
  );
}

/** @internal */
export type CreateTaskAssigneeUnion$Outbound =
  | CreateTaskAssigneeWorkspaceMember$Outbound
  | CreateTaskAssignee$Outbound;

/** @internal */
export const CreateTaskAssigneeUnion$outboundSchema: z.ZodMiniType<
  CreateTaskAssigneeUnion$Outbound,
  CreateTaskAssigneeUnion
> = smartUnion([
  z.lazy(() => CreateTaskAssigneeWorkspaceMember$outboundSchema),
  z.lazy(() => CreateTaskAssignee$outboundSchema),
]);

export function createTaskAssigneeUnionToJSON(
  createTaskAssigneeUnion: CreateTaskAssigneeUnion,
): string {
  return JSON.stringify(
    CreateTaskAssigneeUnion$outboundSchema.parse(createTaskAssigneeUnion),
  );
}

/** @internal */
export type CreateTaskData$Outbound = {
  content: string;
  format: string;
  deadline_at: string | null;
  is_completed: boolean;
  linked_records: Array<
    CreateTaskLinkedRecord1$Outbound | CreateTaskLinkedRecord2$Outbound
  >;
  assignees: Array<
    CreateTaskAssigneeWorkspaceMember$Outbound | CreateTaskAssignee$Outbound
  >;
};

/** @internal */
export const CreateTaskData$outboundSchema: z.ZodMiniType<
  CreateTaskData$Outbound,
  CreateTaskData
> = z.pipe(
  z.object({
    content: z.string(),
    format: CreateTaskFormat$outboundSchema,
    deadlineAt: z.nullable(z.string()),
    isCompleted: z.boolean(),
    linkedRecords: z.array(smartUnion([
      z.lazy(() => CreateTaskLinkedRecord1$outboundSchema),
      z.lazy(() => CreateTaskLinkedRecord2$outboundSchema),
    ])),
    assignees: z.array(smartUnion([
      z.lazy(() => CreateTaskAssigneeWorkspaceMember$outboundSchema),
      z.lazy(() =>
        CreateTaskAssignee$outboundSchema
      ),
    ])),
  }),
  z.transform((v) => {
    return remap$(v, {
      deadlineAt: "deadline_at",
      isCompleted: "is_completed",
      linkedRecords: "linked_records",
    });
  }),
);

export function createTaskDataToJSON(createTaskData: CreateTaskData): string {
  return JSON.stringify(CreateTaskData$outboundSchema.parse(createTaskData));
}

/** @internal */
export type CreateTaskRequest$Outbound = {
  data: CreateTaskData$Outbound;
};

/** @internal */
export const CreateTaskRequest$outboundSchema: z.ZodMiniType<
  CreateTaskRequest$Outbound,
  CreateTaskRequest
> = z.object({
  data: z.lazy(() => CreateTaskData$outboundSchema),
});

export function createTaskRequestToJSON(
  createTaskRequest: CreateTaskRequest,
): string {
  return JSON.stringify(
    CreateTaskRequest$outboundSchema.parse(createTaskRequest),
  );
}

/** @internal */
export const CreateTaskNotFoundStatusCode$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskNotFoundStatusCode
> = z.enum(CreateTaskNotFoundStatusCode);

/** @internal */
export const CreateTaskNotFoundType$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskNotFoundType
> = z.enum(CreateTaskNotFoundType);

/** @internal */
export const CreateTaskNotFoundCode$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskNotFoundCode
> = z.enum(CreateTaskNotFoundCode);

/** @internal */
export const CreateTaskBadRequestStatusCode$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskBadRequestStatusCode
> = z.enum(CreateTaskBadRequestStatusCode);

/** @internal */
export const CreateTaskBadRequestType$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskBadRequestType
> = z.enum(CreateTaskBadRequestType);

/** @internal */
export const CreateTaskCodeValidationType$inboundSchema: z.ZodMiniEnum<
  typeof CreateTaskCodeValidationType
> = z.enum(CreateTaskCodeValidationType);

/** @internal */
export const CreateTaskResponse$inboundSchema: z.ZodMiniType<
  CreateTaskResponse,
  unknown
> = z.object({
  data: models.Task$inboundSchema,
});

export function createTaskResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTaskResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTaskResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTaskResponse' from JSON`,
  );
}
