/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteCallRecordingRequest = {
  meetingId: string;
  callRecordingId: string;
};

/**
 * Success
 */
export type DeleteCallRecordingResponse = {};

/** @internal */
export type DeleteCallRecordingRequest$Outbound = {
  meeting_id: string;
  call_recording_id: string;
};

/** @internal */
export const DeleteCallRecordingRequest$outboundSchema: z.ZodMiniType<
  DeleteCallRecordingRequest$Outbound,
  DeleteCallRecordingRequest
> = z.pipe(
  z.object({
    meetingId: z.string(),
    callRecordingId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      meetingId: "meeting_id",
      callRecordingId: "call_recording_id",
    });
  }),
);

export function deleteCallRecordingRequestToJSON(
  deleteCallRecordingRequest: DeleteCallRecordingRequest,
): string {
  return JSON.stringify(
    DeleteCallRecordingRequest$outboundSchema.parse(deleteCallRecordingRequest),
  );
}

/** @internal */
export const DeleteCallRecordingResponse$inboundSchema: z.ZodMiniType<
  DeleteCallRecordingResponse,
  unknown
> = z.object({});

export function deleteCallRecordingResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteCallRecordingResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteCallRecordingResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteCallRecordingResponse' from JSON`,
  );
}
