/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteScimGroupRequest = {
  workspaceTeamId: string;
};

/**
 * No Content
 */
export type DeleteScimGroupResponse = {};

/** @internal */
export type DeleteScimGroupRequest$Outbound = {
  workspace_team_id: string;
};

/** @internal */
export const DeleteScimGroupRequest$outboundSchema: z.ZodMiniType<
  DeleteScimGroupRequest$Outbound,
  DeleteScimGroupRequest
> = z.pipe(
  z.object({
    workspaceTeamId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      workspaceTeamId: "workspace_team_id",
    });
  }),
);

export function deleteScimGroupRequestToJSON(
  deleteScimGroupRequest: DeleteScimGroupRequest,
): string {
  return JSON.stringify(
    DeleteScimGroupRequest$outboundSchema.parse(deleteScimGroupRequest),
  );
}

/** @internal */
export const DeleteScimGroupResponse$inboundSchema: z.ZodMiniType<
  DeleteScimGroupResponse,
  unknown
> = z.object({});

export function deleteScimGroupResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteScimGroupResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteScimGroupResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteScimGroupResponse' from JSON`,
  );
}
