/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetWebhookRequest = {
  webhookId: string;
};

/**
 * Type of event the webhook is subscribed to.
 */
export const GetWebhookEventType = {
  CallRecordingCreated: "call-recording.created",
  CommentCreated: "comment.created",
  CommentResolved: "comment.resolved",
  CommentUnresolved: "comment.unresolved",
  CommentDeleted: "comment.deleted",
  ListCreated: "list.created",
  ListUpdated: "list.updated",
  ListDeleted: "list.deleted",
  ListAttributeCreated: "list-attribute.created",
  ListAttributeUpdated: "list-attribute.updated",
  ListEntryCreated: "list-entry.created",
  ListEntryUpdated: "list-entry.updated",
  ListEntryDeleted: "list-entry.deleted",
  ObjectAttributeCreated: "object-attribute.created",
  ObjectAttributeUpdated: "object-attribute.updated",
  NoteCreated: "note.created",
  NoteContentUpdated: "note-content.updated",
  NoteUpdated: "note.updated",
  NoteDeleted: "note.deleted",
  RecordCreated: "record.created",
  RecordMerged: "record.merged",
  RecordUpdated: "record.updated",
  RecordDeleted: "record.deleted",
  TaskCreated: "task.created",
  TaskUpdated: "task.updated",
  TaskDeleted: "task.deleted",
  WorkspaceMemberCreated: "workspace-member.created",
} as const;
/**
 * Type of event the webhook is subscribed to.
 */
export type GetWebhookEventType = OpenEnum<typeof GetWebhookEventType>;

export type GetWebhookDollarAndNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetWebhookDollarAndEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetWebhookDollarAndUnion =
  | GetWebhookDollarAndEquals
  | GetWebhookDollarAndNotEquals
  | discriminatedUnionTypes.Unknown<"operator">;

export type GetWebhookFilter2 = {
  dollarAnd: Array<
    | GetWebhookDollarAndEquals
    | GetWebhookDollarAndNotEquals
    | discriminatedUnionTypes.Unknown<"operator">
  >;
};

export type GetWebhookDollarOrNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetWebhookDollarOrEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetWebhookDollarOrUnion =
  | GetWebhookDollarOrEquals
  | GetWebhookDollarOrNotEquals
  | discriminatedUnionTypes.Unknown<"operator">;

export type GetWebhookFilter1 = {
  dollarOr: Array<
    | GetWebhookDollarOrEquals
    | GetWebhookDollarOrNotEquals
    | discriminatedUnionTypes.Unknown<"operator">
  >;
};

/**
 * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
 *
 * @remarks
 *
 * When filters are compared for uniqueness, key order and the order of operations are ignored.
 */
export type GetWebhookFilterUnion = GetWebhookFilter1 | GetWebhookFilter2;

export type GetWebhookSubscription = {
  /**
   * Type of event the webhook is subscribed to.
   */
  eventType: GetWebhookEventType;
  /**
   * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
   *
   * @remarks
   *
   * When filters are compared for uniqueness, key order and the order of operations are ignored.
   */
  filter: GetWebhookFilter1 | GetWebhookFilter2 | null;
};

export type GetWebhookId = {
  /**
   * The ID of the workspace the webhook belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the webhook.
   */
  webhookId: string;
};

/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export const GetWebhookStatus = {
  Active: "active",
  Degraded: "degraded",
  Inactive: "inactive",
} as const;
/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export type GetWebhookStatus = OpenEnum<typeof GetWebhookStatus>;

export type GetWebhookData = {
  /**
   * URL where the webhook events will be delivered to.
   */
  targetUrl: string;
  /**
   * One or more events the webhook is subscribed to.
   *
   * @remarks
   *
   * Within a workspace, the combination of target URL, event type and filter must be unique across all of your webhooks. A duplicate — whether against another webhook or repeated within a single request — is rejected with a `409 uniqueness_conflict`.
   */
  subscriptions: Array<GetWebhookSubscription>;
  id: GetWebhookId;
  /**
   * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
   */
  status: GetWebhookStatus;
  /**
   * When the webhook was created.
   */
  createdAt: string;
};

/**
 * Success
 */
export type GetWebhookResponse = {
  data: GetWebhookData;
};

/** @internal */
export type GetWebhookRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const GetWebhookRequest$outboundSchema: z.ZodMiniType<
  GetWebhookRequest$Outbound,
  GetWebhookRequest
> = z.pipe(
  z.object({
    webhookId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      webhookId: "webhook_id",
    });
  }),
);

export function getWebhookRequestToJSON(
  getWebhookRequest: GetWebhookRequest,
): string {
  return JSON.stringify(
    GetWebhookRequest$outboundSchema.parse(getWebhookRequest),
  );
}

/** @internal */
export const GetWebhookEventType$inboundSchema: z.ZodMiniType<
  GetWebhookEventType,
  unknown
> = openEnums.inboundSchema(GetWebhookEventType);

/** @internal */
export const GetWebhookDollarAndNotEquals$inboundSchema: z.ZodMiniType<
  GetWebhookDollarAndNotEquals,
  unknown
> = z.object({
  field: types.string(),
  operator: types.literal("not_equals"),
  value: types.string(),
});

export function getWebhookDollarAndNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarAndNotEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarAndNotEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarAndNotEquals' from JSON`,
  );
}

/** @internal */
export const GetWebhookDollarAndEquals$inboundSchema: z.ZodMiniType<
  GetWebhookDollarAndEquals,
  unknown
> = z.object({
  field: types.string(),
  operator: types.literal("equals"),
  value: types.string(),
});

export function getWebhookDollarAndEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarAndEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarAndEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarAndEquals' from JSON`,
  );
}

/** @internal */
export const GetWebhookDollarAndUnion$inboundSchema: z.ZodMiniType<
  GetWebhookDollarAndUnion,
  unknown
> = discriminatedUnion("operator", {
  equals: z.lazy(() => GetWebhookDollarAndEquals$inboundSchema),
  not_equals: z.lazy(() => GetWebhookDollarAndNotEquals$inboundSchema),
});

export function getWebhookDollarAndUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarAndUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarAndUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarAndUnion' from JSON`,
  );
}

/** @internal */
export const GetWebhookFilter2$inboundSchema: z.ZodMiniType<
  GetWebhookFilter2,
  unknown
> = z.pipe(
  z.object({
    $and: z.array(discriminatedUnion("operator", {
      equals: z.lazy(() => GetWebhookDollarAndEquals$inboundSchema),
      not_equals: z.lazy(() => GetWebhookDollarAndNotEquals$inboundSchema),
    })),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$and": "dollarAnd",
    });
  }),
);

export function getWebhookFilter2FromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookFilter2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookFilter2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookFilter2' from JSON`,
  );
}

/** @internal */
export const GetWebhookDollarOrNotEquals$inboundSchema: z.ZodMiniType<
  GetWebhookDollarOrNotEquals,
  unknown
> = z.object({
  field: types.string(),
  operator: types.literal("not_equals"),
  value: types.string(),
});

export function getWebhookDollarOrNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarOrNotEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarOrNotEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarOrNotEquals' from JSON`,
  );
}

/** @internal */
export const GetWebhookDollarOrEquals$inboundSchema: z.ZodMiniType<
  GetWebhookDollarOrEquals,
  unknown
> = z.object({
  field: types.string(),
  operator: types.literal("equals"),
  value: types.string(),
});

export function getWebhookDollarOrEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarOrEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarOrEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarOrEquals' from JSON`,
  );
}

/** @internal */
export const GetWebhookDollarOrUnion$inboundSchema: z.ZodMiniType<
  GetWebhookDollarOrUnion,
  unknown
> = discriminatedUnion("operator", {
  equals: z.lazy(() => GetWebhookDollarOrEquals$inboundSchema),
  not_equals: z.lazy(() => GetWebhookDollarOrNotEquals$inboundSchema),
});

export function getWebhookDollarOrUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookDollarOrUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookDollarOrUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookDollarOrUnion' from JSON`,
  );
}

/** @internal */
export const GetWebhookFilter1$inboundSchema: z.ZodMiniType<
  GetWebhookFilter1,
  unknown
> = z.pipe(
  z.object({
    $or: z.array(discriminatedUnion("operator", {
      equals: z.lazy(() => GetWebhookDollarOrEquals$inboundSchema),
      not_equals: z.lazy(() => GetWebhookDollarOrNotEquals$inboundSchema),
    })),
  }),
  z.transform((v) => {
    return remap$(v, {
      "$or": "dollarOr",
    });
  }),
);

export function getWebhookFilter1FromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookFilter1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookFilter1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookFilter1' from JSON`,
  );
}

/** @internal */
export const GetWebhookFilterUnion$inboundSchema: z.ZodMiniType<
  GetWebhookFilterUnion,
  unknown
> = smartUnion([
  z.lazy(() => GetWebhookFilter1$inboundSchema),
  z.lazy(() => GetWebhookFilter2$inboundSchema),
]);

export function getWebhookFilterUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookFilterUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookFilterUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookFilterUnion' from JSON`,
  );
}

/** @internal */
export const GetWebhookSubscription$inboundSchema: z.ZodMiniType<
  GetWebhookSubscription,
  unknown
> = z.pipe(
  z.object({
    event_type: GetWebhookEventType$inboundSchema,
    filter: types.nullable(smartUnion([
      z.lazy(() => GetWebhookFilter1$inboundSchema),
      z.lazy(() => GetWebhookFilter2$inboundSchema),
    ])),
  }),
  z.transform((v) => {
    return remap$(v, {
      "event_type": "eventType",
    });
  }),
);

export function getWebhookSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookSubscription' from JSON`,
  );
}

/** @internal */
export const GetWebhookId$inboundSchema: z.ZodMiniType<GetWebhookId, unknown> =
  z.pipe(
    z.object({
      workspace_id: types.string(),
      webhook_id: types.string(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "workspace_id": "workspaceId",
        "webhook_id": "webhookId",
      });
    }),
  );

export function getWebhookIdFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookId' from JSON`,
  );
}

/** @internal */
export const GetWebhookStatus$inboundSchema: z.ZodMiniType<
  GetWebhookStatus,
  unknown
> = openEnums.inboundSchema(GetWebhookStatus);

/** @internal */
export const GetWebhookData$inboundSchema: z.ZodMiniType<
  GetWebhookData,
  unknown
> = z.pipe(
  z.object({
    target_url: types.string(),
    subscriptions: z.array(z.lazy(() => GetWebhookSubscription$inboundSchema)),
    id: z.lazy(() => GetWebhookId$inboundSchema),
    status: GetWebhookStatus$inboundSchema,
    created_at: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "target_url": "targetUrl",
      "created_at": "createdAt",
    });
  }),
);

export function getWebhookDataFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookData' from JSON`,
  );
}

/** @internal */
export const GetWebhookResponse$inboundSchema: z.ZodMiniType<
  GetWebhookResponse,
  unknown
> = z.object({
  data: z.lazy(() => GetWebhookData$inboundSchema),
});

export function getWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWebhookResponse' from JSON`,
  );
}
