/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetV2TasksTaskIdRequest = {
  taskId: string;
};

export const GetV2TasksTaskIdType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type GetV2TasksTaskIdType = ClosedEnum<typeof GetV2TasksTaskIdType>;

export const GetV2TasksTaskIdCode = {
  NotFound: "not_found",
} as const;
export type GetV2TasksTaskIdCode = ClosedEnum<typeof GetV2TasksTaskIdCode>;

/**
 * Success
 */
export type GetV2TasksTaskIdResponse = {
  data: models.Task;
};

export type DeleteV2TasksTaskIdRequest = {
  taskId: string;
};

/**
 * Success
 */
export type DeleteV2TasksTaskIdResponse = {};

/** @internal */
export type GetV2TasksTaskIdRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const GetV2TasksTaskIdRequest$outboundSchema: z.ZodMiniType<
  GetV2TasksTaskIdRequest$Outbound,
  GetV2TasksTaskIdRequest
> = z.pipe(
  z.object({
    taskId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      taskId: "task_id",
    });
  }),
);

export function getV2TasksTaskIdRequestToJSON(
  getV2TasksTaskIdRequest: GetV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    GetV2TasksTaskIdRequest$outboundSchema.parse(getV2TasksTaskIdRequest),
  );
}

/** @internal */
export const GetV2TasksTaskIdType$inboundSchema: z.ZodMiniEnum<
  typeof GetV2TasksTaskIdType
> = z.enum(GetV2TasksTaskIdType);

/** @internal */
export const GetV2TasksTaskIdCode$inboundSchema: z.ZodMiniEnum<
  typeof GetV2TasksTaskIdCode
> = z.enum(GetV2TasksTaskIdCode);

/** @internal */
export const GetV2TasksTaskIdResponse$inboundSchema: z.ZodMiniType<
  GetV2TasksTaskIdResponse,
  unknown
> = z.object({
  data: models.Task$inboundSchema,
});

export function getV2TasksTaskIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2TasksTaskIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2TasksTaskIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2TasksTaskIdResponse' from JSON`,
  );
}

/** @internal */
export type DeleteV2TasksTaskIdRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const DeleteV2TasksTaskIdRequest$outboundSchema: z.ZodMiniType<
  DeleteV2TasksTaskIdRequest$Outbound,
  DeleteV2TasksTaskIdRequest
> = z.pipe(
  z.object({
    taskId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      taskId: "task_id",
    });
  }),
);

export function deleteV2TasksTaskIdRequestToJSON(
  deleteV2TasksTaskIdRequest: DeleteV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    DeleteV2TasksTaskIdRequest$outboundSchema.parse(deleteV2TasksTaskIdRequest),
  );
}

/** @internal */
export const DeleteV2TasksTaskIdResponse$inboundSchema: z.ZodMiniType<
  DeleteV2TasksTaskIdResponse,
  unknown
> = z.object({});

export function deleteV2TasksTaskIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2TasksTaskIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2TasksTaskIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2TasksTaskIdResponse' from JSON`,
  );
}
