/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetListRequest = {
  list: string;
};

export const GetListStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type GetListStatusCode = ClosedEnum<typeof GetListStatusCode>;

export const GetListType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type GetListType = ClosedEnum<typeof GetListType>;

export const GetListCode = {
  NotFound: "not_found",
} as const;
export type GetListCode = ClosedEnum<typeof GetListCode>;

/**
 * Success
 */
export type GetListResponse = {
  data: models.List;
};

/** @internal */
export type GetListRequest$Outbound = {
  list: string;
};

/** @internal */
export const GetListRequest$outboundSchema: z.ZodMiniType<
  GetListRequest$Outbound,
  GetListRequest
> = z.object({
  list: z.string(),
});

export function getListRequestToJSON(getListRequest: GetListRequest): string {
  return JSON.stringify(GetListRequest$outboundSchema.parse(getListRequest));
}

/** @internal */
export const GetListStatusCode$inboundSchema: z.ZodMiniEnum<
  typeof GetListStatusCode
> = z.enum(GetListStatusCode);

/** @internal */
export const GetListType$inboundSchema: z.ZodMiniEnum<typeof GetListType> = z
  .enum(GetListType);

/** @internal */
export const GetListCode$inboundSchema: z.ZodMiniEnum<typeof GetListCode> = z
  .enum(GetListCode);

/** @internal */
export const GetListResponse$inboundSchema: z.ZodMiniType<
  GetListResponse,
  unknown
> = z.object({
  data: models.List$inboundSchema,
});

export function getListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetListResponse' from JSON`,
  );
}
