/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Success
 */
export type GetV2ObjectsResponse = {
  data: Array<models.ObjectT>;
};

/** @internal */
export const GetV2ObjectsResponse$inboundSchema: z.ZodMiniType<
  GetV2ObjectsResponse,
  unknown
> = z.object({
  data: z.array(models.ObjectT$inboundSchema),
});

export function getV2ObjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ObjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsResponse' from JSON`,
  );
}
