/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * The external storage provider.
 */
export const PostV2FilesStorageProvider2 = {
  Dropbox: "dropbox",
  Box: "box",
  GoogleDrive: "google-drive",
  MicrosoftOnedrive: "microsoft-onedrive",
} as const;
/**
 * The external storage provider.
 */
export type PostV2FilesStorageProvider2 = ClosedEnum<
  typeof PostV2FilesStorageProvider2
>;

export type ConnectedFile = {
  /**
   * The object slug or ID.
   */
  object: string;
  /**
   * The ID of the record to create the file entry on.
   */
  recordId: string;
  /**
   * The external storage provider.
   */
  storageProvider: PostV2FilesStorageProvider2;
  /**
   * The ID of the file or folder in the external storage provider.
   */
  externalProviderFileId: string;
  /**
   * Microsoft drive ID. Only used when `storage_provider` is `microsoft-onedrive`.
   */
  microsoftDriveId?: string | null | undefined;
  /**
   * Creates a connected file entry.
   */
  fileType: "connected-file";
};

/**
 * The external storage provider.
 */
export const PostV2FilesStorageProvider1 = {
  Dropbox: "dropbox",
  Box: "box",
  GoogleDrive: "google-drive",
  MicrosoftOnedrive: "microsoft-onedrive",
} as const;
/**
 * The external storage provider.
 */
export type PostV2FilesStorageProvider1 = ClosedEnum<
  typeof PostV2FilesStorageProvider1
>;

export type ConnectedFolder = {
  /**
   * The object slug or ID.
   */
  object: string;
  /**
   * The ID of the record to create the file entry on.
   */
  recordId: string;
  /**
   * The external storage provider.
   */
  storageProvider: PostV2FilesStorageProvider1;
  /**
   * The ID of the file or folder in the external storage provider.
   */
  externalProviderFileId: string;
  /**
   * Microsoft drive ID. Only used when `storage_provider` is `microsoft-onedrive`.
   */
  microsoftDriveId?: string | null | undefined;
  /**
   * Creates a connected folder entry.
   */
  fileType: "connected-folder";
};

export type PostV2FilesFolder = {
  /**
   * The object slug or ID.
   */
  object: string;
  /**
   * The ID of the record to create the file entry on.
   */
  recordId: string;
  /**
   * Creates a native Attio folder entry.
   */
  fileType: "folder";
  /**
   * The folder name.
   */
  name: string;
  /**
   * Optional parent folder ID. Omit to create a top-level folder.
   */
  parentFolderId?: string | undefined;
};

export type PostV2FilesRequest =
  | PostV2FilesFolder
  | ConnectedFolder
  | ConnectedFile;

export type PostV2FilesData =
  | models.Folder
  | models.ConnectedFile
  | models.ConnectedFolder
  | discriminatedUnionTypes.Unknown<"fileType">;

/**
 * Success
 */
export type PostV2FilesResponse = {
  data:
    | models.Folder
    | models.ConnectedFile
    | models.ConnectedFolder
    | discriminatedUnionTypes.Unknown<"fileType">;
};

/** @internal */
export const PostV2FilesStorageProvider2$outboundSchema: z.ZodMiniEnum<
  typeof PostV2FilesStorageProvider2
> = z.enum(PostV2FilesStorageProvider2);

/** @internal */
export type ConnectedFile$Outbound = {
  object: string;
  record_id: string;
  storage_provider: string;
  external_provider_file_id: string;
  microsoft_drive_id?: string | null | undefined;
  file_type: "connected-file";
};

/** @internal */
export const ConnectedFile$outboundSchema: z.ZodMiniType<
  ConnectedFile$Outbound,
  ConnectedFile
> = z.pipe(
  z.object({
    object: z.string(),
    recordId: z.string(),
    storageProvider: PostV2FilesStorageProvider2$outboundSchema,
    externalProviderFileId: z.string(),
    microsoftDriveId: z.optional(z.nullable(z.string())),
    fileType: z.literal("connected-file"),
  }),
  z.transform((v) => {
    return remap$(v, {
      recordId: "record_id",
      storageProvider: "storage_provider",
      externalProviderFileId: "external_provider_file_id",
      microsoftDriveId: "microsoft_drive_id",
      fileType: "file_type",
    });
  }),
);

export function connectedFileToJSON(connectedFile: ConnectedFile): string {
  return JSON.stringify(ConnectedFile$outboundSchema.parse(connectedFile));
}

/** @internal */
export const PostV2FilesStorageProvider1$outboundSchema: z.ZodMiniEnum<
  typeof PostV2FilesStorageProvider1
> = z.enum(PostV2FilesStorageProvider1);

/** @internal */
export type ConnectedFolder$Outbound = {
  object: string;
  record_id: string;
  storage_provider: string;
  external_provider_file_id: string;
  microsoft_drive_id?: string | null | undefined;
  file_type: "connected-folder";
};

/** @internal */
export const ConnectedFolder$outboundSchema: z.ZodMiniType<
  ConnectedFolder$Outbound,
  ConnectedFolder
> = z.pipe(
  z.object({
    object: z.string(),
    recordId: z.string(),
    storageProvider: PostV2FilesStorageProvider1$outboundSchema,
    externalProviderFileId: z.string(),
    microsoftDriveId: z.optional(z.nullable(z.string())),
    fileType: z.literal("connected-folder"),
  }),
  z.transform((v) => {
    return remap$(v, {
      recordId: "record_id",
      storageProvider: "storage_provider",
      externalProviderFileId: "external_provider_file_id",
      microsoftDriveId: "microsoft_drive_id",
      fileType: "file_type",
    });
  }),
);

export function connectedFolderToJSON(
  connectedFolder: ConnectedFolder,
): string {
  return JSON.stringify(ConnectedFolder$outboundSchema.parse(connectedFolder));
}

/** @internal */
export type PostV2FilesFolder$Outbound = {
  object: string;
  record_id: string;
  file_type: "folder";
  name: string;
  parent_folder_id?: string | undefined;
};

/** @internal */
export const PostV2FilesFolder$outboundSchema: z.ZodMiniType<
  PostV2FilesFolder$Outbound,
  PostV2FilesFolder
> = z.pipe(
  z.object({
    object: z.string(),
    recordId: z.string(),
    fileType: z.literal("folder"),
    name: z.string(),
    parentFolderId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      recordId: "record_id",
      fileType: "file_type",
      parentFolderId: "parent_folder_id",
    });
  }),
);

export function postV2FilesFolderToJSON(
  postV2FilesFolder: PostV2FilesFolder,
): string {
  return JSON.stringify(
    PostV2FilesFolder$outboundSchema.parse(postV2FilesFolder),
  );
}

/** @internal */
export type PostV2FilesRequest$Outbound =
  | PostV2FilesFolder$Outbound
  | ConnectedFolder$Outbound
  | ConnectedFile$Outbound;

/** @internal */
export const PostV2FilesRequest$outboundSchema: z.ZodMiniType<
  PostV2FilesRequest$Outbound,
  PostV2FilesRequest
> = z.union([
  z.lazy(() => PostV2FilesFolder$outboundSchema),
  z.lazy(() => ConnectedFolder$outboundSchema),
  z.lazy(() => ConnectedFile$outboundSchema),
]);

export function postV2FilesRequestToJSON(
  postV2FilesRequest: PostV2FilesRequest,
): string {
  return JSON.stringify(
    PostV2FilesRequest$outboundSchema.parse(postV2FilesRequest),
  );
}

/** @internal */
export const PostV2FilesData$inboundSchema: z.ZodMiniType<
  PostV2FilesData,
  unknown
> = discriminatedUnion("file_type", {
  folder: models.Folder$inboundSchema,
  ["connected-file"]: models.ConnectedFile$inboundSchema,
  ["connected-folder"]: models.ConnectedFolder$inboundSchema,
}, { outputPropertyName: "fileType" });

export function postV2FilesDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV2FilesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2FilesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2FilesData' from JSON`,
  );
}

/** @internal */
export const PostV2FilesResponse$inboundSchema: z.ZodMiniType<
  PostV2FilesResponse,
  unknown
> = z.object({
  data: discriminatedUnion("file_type", {
    folder: models.Folder$inboundSchema,
    ["connected-file"]: models.ConnectedFile$inboundSchema,
    ["connected-folder"]: models.ConnectedFolder$inboundSchema,
  }, { outputPropertyName: "fileType" }),
});

export function postV2FilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2FilesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2FilesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2FilesResponse' from JSON`,
  );
}
