/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Name = {
  givenName: string;
  familyName: string;
};

export type Email = {
  value: string;
  primary: boolean;
  type?: string | undefined;
};

export type Role = {
  value: string;
  primary: boolean;
};

export type PostScimV2UsersMeta = {
  resourceType: string;
  created: string;
  lastModified: string;
};

/**
 * Created
 */
export type PostScimV2UsersResponse = {
  schemas: Array<string>;
  id: string;
  userName: string;
  name: Name;
  emails: Array<Email>;
  roles: Array<Role>;
  profileUrl?: string | undefined;
  active: boolean;
  meta: PostScimV2UsersMeta;
};

/** @internal */
export const Name$inboundSchema: z.ZodMiniType<Name, unknown> = z.object({
  givenName: types.string(),
  familyName: types.string(),
});

export function nameFromJSON(
  jsonString: string,
): SafeParseResult<Name, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Name$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Name' from JSON`,
  );
}

/** @internal */
export const Email$inboundSchema: z.ZodMiniType<Email, unknown> = z.object({
  value: types.string(),
  primary: types.boolean(),
  type: types.optional(types.string()),
});

export function emailFromJSON(
  jsonString: string,
): SafeParseResult<Email, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Email$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Email' from JSON`,
  );
}

/** @internal */
export const Role$inboundSchema: z.ZodMiniType<Role, unknown> = z.object({
  value: types.string(),
  primary: types.boolean(),
});

export function roleFromJSON(
  jsonString: string,
): SafeParseResult<Role, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Role$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Role' from JSON`,
  );
}

/** @internal */
export const PostScimV2UsersMeta$inboundSchema: z.ZodMiniType<
  PostScimV2UsersMeta,
  unknown
> = z.object({
  resourceType: types.string(),
  created: types.string(),
  lastModified: types.string(),
});

export function postScimV2UsersMetaFromJSON(
  jsonString: string,
): SafeParseResult<PostScimV2UsersMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostScimV2UsersMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostScimV2UsersMeta' from JSON`,
  );
}

/** @internal */
export const PostScimV2UsersResponse$inboundSchema: z.ZodMiniType<
  PostScimV2UsersResponse,
  unknown
> = z.object({
  schemas: z.array(types.string()),
  id: types.string(),
  userName: types.string(),
  name: z.lazy(() => Name$inboundSchema),
  emails: z.array(z.lazy(() => Email$inboundSchema)),
  roles: z.array(z.lazy(() => Role$inboundSchema)),
  profileUrl: types.optional(types.string()),
  active: types.boolean(),
  meta: z.lazy(() => PostScimV2UsersMeta$inboundSchema),
});

export function postScimV2UsersResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostScimV2UsersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostScimV2UsersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostScimV2UsersResponse' from JSON`,
  );
}
