/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { blobLikeSchema } from "../../types/blobs.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type FileT = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type PostV2FilesUploadRequest = {
  /**
   * The file to upload.
   */
  file: FileT | Blob;
  /**
   * The object slug or ID.
   */
  object: string;
  /**
   * The ID of the record to upload the file to.
   */
  recordId: string;
  /**
   * Optional parent folder ID. Omit to upload to the root folder.
   */
  parentFolderId?: string | undefined;
};

/**
 * Created
 */
export type PostV2FilesUploadResponse = {
  data: models.FileT;
};

/** @internal */
export type FileT$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const FileT$outboundSchema: z.ZodMiniType<FileT$Outbound, FileT> = z
  .object({
    fileName: z.string(),
    content: z.union([
      z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
      z.custom<Blob>(x => x instanceof Blob),
      z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
      z.custom<Uint8Array>(x => x instanceof Uint8Array),
    ]),
  });

export function fileToJSON(fileT: FileT): string {
  return JSON.stringify(FileT$outboundSchema.parse(fileT));
}

/** @internal */
export type PostV2FilesUploadRequest$Outbound = {
  file: FileT$Outbound | Blob;
  object: string;
  record_id: string;
  parent_folder_id?: string | undefined;
};

/** @internal */
export const PostV2FilesUploadRequest$outboundSchema: z.ZodMiniType<
  PostV2FilesUploadRequest$Outbound,
  PostV2FilesUploadRequest
> = z.pipe(
  z.object({
    file: z.union([z.lazy(() => FileT$outboundSchema), blobLikeSchema]),
    object: z.string(),
    recordId: z.string(),
    parentFolderId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      recordId: "record_id",
      parentFolderId: "parent_folder_id",
    });
  }),
);

export function postV2FilesUploadRequestToJSON(
  postV2FilesUploadRequest: PostV2FilesUploadRequest,
): string {
  return JSON.stringify(
    PostV2FilesUploadRequest$outboundSchema.parse(postV2FilesUploadRequest),
  );
}

/** @internal */
export const PostV2FilesUploadResponse$inboundSchema: z.ZodMiniType<
  PostV2FilesUploadResponse,
  unknown
> = z.object({
  data: models.FileT$inboundSchema,
});

export function postV2FilesUploadResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2FilesUploadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2FilesUploadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2FilesUploadResponse' from JSON`,
  );
}
