/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export const PostV2ListsWorkspaceAccess = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export type PostV2ListsWorkspaceAccess = ClosedEnum<
  typeof PostV2ListsWorkspaceAccess
>;

/**
 * The level of access to the list.
 */
export const PostV2ListsLevel = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access to the list.
 */
export type PostV2ListsLevel = ClosedEnum<typeof PostV2ListsLevel>;

export type PostV2ListsWorkspaceMemberAccess = {
  /**
   * A UUID to identify the workspace member to grant access to.
   */
  workspaceMemberId: string;
  /**
   * The level of access to the list.
   */
  level: PostV2ListsLevel;
};

export type PostV2ListsData = {
  /**
   * The human-readable name of the list.
   */
  name: string;
  /**
   * A unique, human-readable slug to access the list through API calls. Should be formatted in snake case.
   */
  apiSlug: string;
  /**
   * A UUID or slug to identify the allowed object type for records added to this list.
   */
  parentObject: string;
  /**
   * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
   */
  workspaceAccess: PostV2ListsWorkspaceAccess | null;
  /**
   * The level of access granted to specific workspace members for this list. Pass an empty array to grant access to no workspace members.
   */
  workspaceMemberAccess: Array<PostV2ListsWorkspaceMemberAccess>;
};

export type PostV2ListsRequest = {
  data: PostV2ListsData;
};

export const PostV2ListsConflictType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type PostV2ListsConflictType = ClosedEnum<
  typeof PostV2ListsConflictType
>;

export const PostV2ListsConflictCode = {
  SlugConflict: "slug_conflict",
} as const;
export type PostV2ListsConflictCode = ClosedEnum<
  typeof PostV2ListsConflictCode
>;

export const PostV2ListsNotFoundType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type PostV2ListsNotFoundType = ClosedEnum<
  typeof PostV2ListsNotFoundType
>;

export const PostV2ListsNotFoundCode = {
  NotFound: "not_found",
} as const;
export type PostV2ListsNotFoundCode = ClosedEnum<
  typeof PostV2ListsNotFoundCode
>;

export const PostV2ListsForbiddenType = {
  AuthError: "auth_error",
} as const;
export type PostV2ListsForbiddenType = ClosedEnum<
  typeof PostV2ListsForbiddenType
>;

export const PostV2ListsCodeBillingError = {
  BillingError: "billing_error",
} as const;
export type PostV2ListsCodeBillingError = ClosedEnum<
  typeof PostV2ListsCodeBillingError
>;

export const PostV2ListsBadRequestType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type PostV2ListsBadRequestType = ClosedEnum<
  typeof PostV2ListsBadRequestType
>;

export const PostV2ListsCodeValueNotFound = {
  ValueNotFound: "value_not_found",
} as const;
export type PostV2ListsCodeValueNotFound = ClosedEnum<
  typeof PostV2ListsCodeValueNotFound
>;

/**
 * Success
 */
export type PostV2ListsResponse = {
  data: models.List;
};

export type GetV2ListsListRequest = {
  list: string;
};

export const GetV2ListsListType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type GetV2ListsListType = ClosedEnum<typeof GetV2ListsListType>;

export const GetV2ListsListCode = {
  NotFound: "not_found",
} as const;
export type GetV2ListsListCode = ClosedEnum<typeof GetV2ListsListCode>;

/**
 * Success
 */
export type GetV2ListsListResponse = {
  data: models.List;
};

/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export const PatchV2ListsListWorkspaceAccess = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export type PatchV2ListsListWorkspaceAccess = ClosedEnum<
  typeof PatchV2ListsListWorkspaceAccess
>;

/**
 * The level of access to the list.
 */
export const PatchV2ListsListLevel = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access to the list.
 */
export type PatchV2ListsListLevel = ClosedEnum<typeof PatchV2ListsListLevel>;

export type PatchV2ListsListWorkspaceMemberAccess = {
  /**
   * A UUID to identify the workspace member to grant access to.
   */
  workspaceMemberId: string;
  /**
   * The level of access to the list.
   */
  level: PatchV2ListsListLevel;
};

export type PatchV2ListsListData = {
  /**
   * The human-readable name of the list.
   */
  name?: string | undefined;
  /**
   * A unique, human-readable slug to access the list through API calls. Should be formatted in snake case.
   */
  apiSlug?: string | undefined;
  /**
   * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
   */
  workspaceAccess?: PatchV2ListsListWorkspaceAccess | null | undefined;
  /**
   * The level of access granted to specific workspace members for this list. Pass an empty array to grant access to no workspace members.
   */
  workspaceMemberAccess?:
    | Array<PatchV2ListsListWorkspaceMemberAccess>
    | undefined;
};

export type PatchV2ListsListRequestBody = {
  data: PatchV2ListsListData;
};

export type PatchV2ListsListRequest = {
  list: string;
  body: PatchV2ListsListRequestBody;
};

/**
 * Success
 */
export type PatchV2ListsListResponse = {
  data: models.List;
};

/** @internal */
export const PostV2ListsWorkspaceAccess$outboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsWorkspaceAccess
> = z.enum(PostV2ListsWorkspaceAccess);

/** @internal */
export const PostV2ListsLevel$outboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsLevel
> = z.enum(PostV2ListsLevel);

/** @internal */
export type PostV2ListsWorkspaceMemberAccess$Outbound = {
  workspace_member_id: string;
  level: string;
};

/** @internal */
export const PostV2ListsWorkspaceMemberAccess$outboundSchema: z.ZodMiniType<
  PostV2ListsWorkspaceMemberAccess$Outbound,
  PostV2ListsWorkspaceMemberAccess
> = z.pipe(
  z.object({
    workspaceMemberId: z.string(),
    level: PostV2ListsLevel$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      workspaceMemberId: "workspace_member_id",
    });
  }),
);

export function postV2ListsWorkspaceMemberAccessToJSON(
  postV2ListsWorkspaceMemberAccess: PostV2ListsWorkspaceMemberAccess,
): string {
  return JSON.stringify(
    PostV2ListsWorkspaceMemberAccess$outboundSchema.parse(
      postV2ListsWorkspaceMemberAccess,
    ),
  );
}

/** @internal */
export type PostV2ListsData$Outbound = {
  name: string;
  api_slug: string;
  parent_object: string;
  workspace_access: string | null;
  workspace_member_access: Array<PostV2ListsWorkspaceMemberAccess$Outbound>;
};

/** @internal */
export const PostV2ListsData$outboundSchema: z.ZodMiniType<
  PostV2ListsData$Outbound,
  PostV2ListsData
> = z.pipe(
  z.object({
    name: z.string(),
    apiSlug: z.string(),
    parentObject: z.string(),
    workspaceAccess: z.nullable(PostV2ListsWorkspaceAccess$outboundSchema),
    workspaceMemberAccess: z.array(
      z.lazy(() => PostV2ListsWorkspaceMemberAccess$outboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiSlug: "api_slug",
      parentObject: "parent_object",
      workspaceAccess: "workspace_access",
      workspaceMemberAccess: "workspace_member_access",
    });
  }),
);

export function postV2ListsDataToJSON(
  postV2ListsData: PostV2ListsData,
): string {
  return JSON.stringify(PostV2ListsData$outboundSchema.parse(postV2ListsData));
}

/** @internal */
export type PostV2ListsRequest$Outbound = {
  data: PostV2ListsData$Outbound;
};

/** @internal */
export const PostV2ListsRequest$outboundSchema: z.ZodMiniType<
  PostV2ListsRequest$Outbound,
  PostV2ListsRequest
> = z.object({
  data: z.lazy(() => PostV2ListsData$outboundSchema),
});

export function postV2ListsRequestToJSON(
  postV2ListsRequest: PostV2ListsRequest,
): string {
  return JSON.stringify(
    PostV2ListsRequest$outboundSchema.parse(postV2ListsRequest),
  );
}

/** @internal */
export const PostV2ListsConflictType$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsConflictType
> = z.enum(PostV2ListsConflictType);

/** @internal */
export const PostV2ListsConflictCode$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsConflictCode
> = z.enum(PostV2ListsConflictCode);

/** @internal */
export const PostV2ListsNotFoundType$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsNotFoundType
> = z.enum(PostV2ListsNotFoundType);

/** @internal */
export const PostV2ListsNotFoundCode$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsNotFoundCode
> = z.enum(PostV2ListsNotFoundCode);

/** @internal */
export const PostV2ListsForbiddenType$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsForbiddenType
> = z.enum(PostV2ListsForbiddenType);

/** @internal */
export const PostV2ListsCodeBillingError$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsCodeBillingError
> = z.enum(PostV2ListsCodeBillingError);

/** @internal */
export const PostV2ListsBadRequestType$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsBadRequestType
> = z.enum(PostV2ListsBadRequestType);

/** @internal */
export const PostV2ListsCodeValueNotFound$inboundSchema: z.ZodMiniEnum<
  typeof PostV2ListsCodeValueNotFound
> = z.enum(PostV2ListsCodeValueNotFound);

/** @internal */
export const PostV2ListsResponse$inboundSchema: z.ZodMiniType<
  PostV2ListsResponse,
  unknown
> = z.object({
  data: models.List$inboundSchema,
});

export function postV2ListsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ListsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ListsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ListsResponse' from JSON`,
  );
}

/** @internal */
export type GetV2ListsListRequest$Outbound = {
  list: string;
};

/** @internal */
export const GetV2ListsListRequest$outboundSchema: z.ZodMiniType<
  GetV2ListsListRequest$Outbound,
  GetV2ListsListRequest
> = z.object({
  list: z.string(),
});

export function getV2ListsListRequestToJSON(
  getV2ListsListRequest: GetV2ListsListRequest,
): string {
  return JSON.stringify(
    GetV2ListsListRequest$outboundSchema.parse(getV2ListsListRequest),
  );
}

/** @internal */
export const GetV2ListsListType$inboundSchema: z.ZodMiniEnum<
  typeof GetV2ListsListType
> = z.enum(GetV2ListsListType);

/** @internal */
export const GetV2ListsListCode$inboundSchema: z.ZodMiniEnum<
  typeof GetV2ListsListCode
> = z.enum(GetV2ListsListCode);

/** @internal */
export const GetV2ListsListResponse$inboundSchema: z.ZodMiniType<
  GetV2ListsListResponse,
  unknown
> = z.object({
  data: models.List$inboundSchema,
});

export function getV2ListsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ListsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ListsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ListsListResponse' from JSON`,
  );
}

/** @internal */
export const PatchV2ListsListWorkspaceAccess$outboundSchema: z.ZodMiniEnum<
  typeof PatchV2ListsListWorkspaceAccess
> = z.enum(PatchV2ListsListWorkspaceAccess);

/** @internal */
export const PatchV2ListsListLevel$outboundSchema: z.ZodMiniEnum<
  typeof PatchV2ListsListLevel
> = z.enum(PatchV2ListsListLevel);

/** @internal */
export type PatchV2ListsListWorkspaceMemberAccess$Outbound = {
  workspace_member_id: string;
  level: string;
};

/** @internal */
export const PatchV2ListsListWorkspaceMemberAccess$outboundSchema:
  z.ZodMiniType<
    PatchV2ListsListWorkspaceMemberAccess$Outbound,
    PatchV2ListsListWorkspaceMemberAccess
  > = z.pipe(
    z.object({
      workspaceMemberId: z.string(),
      level: PatchV2ListsListLevel$outboundSchema,
    }),
    z.transform((v) => {
      return remap$(v, {
        workspaceMemberId: "workspace_member_id",
      });
    }),
  );

export function patchV2ListsListWorkspaceMemberAccessToJSON(
  patchV2ListsListWorkspaceMemberAccess: PatchV2ListsListWorkspaceMemberAccess,
): string {
  return JSON.stringify(
    PatchV2ListsListWorkspaceMemberAccess$outboundSchema.parse(
      patchV2ListsListWorkspaceMemberAccess,
    ),
  );
}

/** @internal */
export type PatchV2ListsListData$Outbound = {
  name?: string | undefined;
  api_slug?: string | undefined;
  workspace_access?: string | null | undefined;
  workspace_member_access?:
    | Array<PatchV2ListsListWorkspaceMemberAccess$Outbound>
    | undefined;
};

/** @internal */
export const PatchV2ListsListData$outboundSchema: z.ZodMiniType<
  PatchV2ListsListData$Outbound,
  PatchV2ListsListData
> = z.pipe(
  z.object({
    name: z.optional(z.string()),
    apiSlug: z.optional(z.string()),
    workspaceAccess: z.optional(
      z.nullable(PatchV2ListsListWorkspaceAccess$outboundSchema),
    ),
    workspaceMemberAccess: z.optional(
      z.array(
        z.lazy(() => PatchV2ListsListWorkspaceMemberAccess$outboundSchema),
      ),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      apiSlug: "api_slug",
      workspaceAccess: "workspace_access",
      workspaceMemberAccess: "workspace_member_access",
    });
  }),
);

export function patchV2ListsListDataToJSON(
  patchV2ListsListData: PatchV2ListsListData,
): string {
  return JSON.stringify(
    PatchV2ListsListData$outboundSchema.parse(patchV2ListsListData),
  );
}

/** @internal */
export type PatchV2ListsListRequestBody$Outbound = {
  data: PatchV2ListsListData$Outbound;
};

/** @internal */
export const PatchV2ListsListRequestBody$outboundSchema: z.ZodMiniType<
  PatchV2ListsListRequestBody$Outbound,
  PatchV2ListsListRequestBody
> = z.object({
  data: z.lazy(() => PatchV2ListsListData$outboundSchema),
});

export function patchV2ListsListRequestBodyToJSON(
  patchV2ListsListRequestBody: PatchV2ListsListRequestBody,
): string {
  return JSON.stringify(
    PatchV2ListsListRequestBody$outboundSchema.parse(
      patchV2ListsListRequestBody,
    ),
  );
}

/** @internal */
export type PatchV2ListsListRequest$Outbound = {
  list: string;
  body: PatchV2ListsListRequestBody$Outbound;
};

/** @internal */
export const PatchV2ListsListRequest$outboundSchema: z.ZodMiniType<
  PatchV2ListsListRequest$Outbound,
  PatchV2ListsListRequest
> = z.object({
  list: z.string(),
  body: z.lazy(() => PatchV2ListsListRequestBody$outboundSchema),
});

export function patchV2ListsListRequestToJSON(
  patchV2ListsListRequest: PatchV2ListsListRequest,
): string {
  return JSON.stringify(
    PatchV2ListsListRequest$outboundSchema.parse(patchV2ListsListRequest),
  );
}

/** @internal */
export const PatchV2ListsListResponse$inboundSchema: z.ZodMiniType<
  PatchV2ListsListResponse,
  unknown
> = z.object({
  data: models.List$inboundSchema,
});

export function patchV2ListsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2ListsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchV2ListsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2ListsListResponse' from JSON`,
  );
}
