/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as discriminatedUnionTypes from "../../types/discriminated-union.js";
import { discriminatedUnion } from "../../types/discriminated-union.js";
import * as openEnums from "../../types/enums.js";
import { ClosedEnum, OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * The direction to sort the results by.
 */
export const QueryEntriesDirection2 = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The direction to sort the results by.
 */
export type QueryEntriesDirection2 = ClosedEnum<typeof QueryEntriesDirection2>;

/**
 * Sort by path
 */
export type QueryEntriesSort2 = {
  /**
   * The direction to sort the results by.
   */
  direction: QueryEntriesDirection2;
  /**
   * You may use the `path` property to traverse record reference attributes and parent records on list entries. `path` accepts an array of tuples where the first element of each tuple is the slug or ID of a list/object, and the second element is the slug or ID of an attribute on that list/object. The first element of the first tuple must correspond to the list or object that you are querying. For example, if you wanted to sort by the name of the parent record (a company) on a list with the slug "sales", you would pass the value `[['sales', 'parent_record'], ['companies', 'name']]`.
   */
  path: Array<Array<string>>;
  /**
   * Which field on the value to sort by e.g. "last_name" on a name value.
   */
  field?: string | undefined;
};

/**
 * The direction to sort the results by.
 */
export const QueryEntriesDirection1 = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The direction to sort the results by.
 */
export type QueryEntriesDirection1 = ClosedEnum<typeof QueryEntriesDirection1>;

/**
 * Sort by attribute
 */
export type QueryEntriesSort1 = {
  /**
   * The direction to sort the results by.
   */
  direction: QueryEntriesDirection1;
  /**
   * A slug or ID to identify the attribute to sort by.
   */
  attribute: string;
  /**
   * Which field on the value to sort by e.g. "last_name" on a name value.
   */
  field?: string | undefined;
};

export type QueryEntriesSortUnion = QueryEntriesSort1 | QueryEntriesSort2;

export type QueryEntriesRequestBody = {
  /**
   * An object used to filter results to a subset of results. Cannot be used together with `filter_view_id`. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
   */
  filter?: { [k: string]: any } | undefined;
  /**
   * UUID of a saved view on this object or list. When set, results are filtered using that view's filter configuration. Cannot be used together with `filter`. Note: sorts, limits, and offsets are applied independently and are not taken from the view. All attributes are returned regardless of which attributes are visible in the view.
   */
  filterViewId?: string | undefined;
  /**
   * An object used to sort results. See the [full guide to filtering and sorting here](/rest-api/guides/filtering-and-sorting).
   */
  sorts?: Array<QueryEntriesSort1 | QueryEntriesSort2> | undefined;
  /**
   * The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/rest-api/guides/pagination).
   */
  limit?: number | undefined;
  /**
   * The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/rest-api/guides/pagination).
   */
  offset?: number | undefined;
};

export type QueryEntriesRequest = {
  list: string;
  body: QueryEntriesRequestBody;
};

export type QueryEntriesId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType17 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType17 = OpenEnum<
  typeof QueryEntriesCreatedByActorType17
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor17 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType17 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueTimestamp = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor17;
  /**
   * The attribute type of the value.
   */
  attributeType: "timestamp";
  /**
   * A timestamp value represents a single, universal moment in time using an ISO 8601 formatted string. This means that a timestamp consists of a date, a time (with nanosecond precision), and a time zone. Attio will coerce timestamps which do not provide full nanosecond precision and UTC is assumed if no time zone is provided. For example, "2023", "2023-01", "2023-01-02", "2023-01-02T13:00", "2023-01-02T13:00:00", and "2023-01-02T13:00:00.000000000" will all be coerced to "2023-01-02T13:00:00.000000000Z". Timestamps are always returned in UTC. For example, writing a timestamp value using the string "2023-01-02T13:00:00.000000000+02:00" will result in the value "2023-01-02T11:00:00.000000000Z" being returned. The maximum date is "9999-12-31T23:59:59.999999999Z".
   */
  value: Date;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType16 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType16 = OpenEnum<
  typeof QueryEntriesCreatedByActorType16
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor16 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType16 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueText = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor16;
  /**
   * A raw text field. Values are limited to 10MB.
   */
  value: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "text";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType15 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType15 = OpenEnum<
  typeof QueryEntriesCreatedByActorType15
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor15 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType15 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueSelect = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor15;
  option: models.SelectOption;
  /**
   * The attribute type of the value.
   */
  attributeType: "select";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType14 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType14 = OpenEnum<
  typeof QueryEntriesCreatedByActorType14
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor14 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType14 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueRating = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor14;
  /**
   * A number between 0 and 5 (inclusive) to represent a star rating.
   */
  value: number;
  /**
   * The attribute type of the value.
   */
  attributeType: "rating";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType13 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType13 = OpenEnum<
  typeof QueryEntriesCreatedByActorType13
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor13 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType13 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueStatus = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor13;
  status: models.Status;
  /**
   * The attribute type of the value.
   */
  attributeType: "status";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType12 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType12 = OpenEnum<
  typeof QueryEntriesCreatedByActorType12
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor12 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType12 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export const QueryEntriesCountryCode2 = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Bq: "BQ",
  Kp: "KP",
  Sx: "SX",
  Xk: "XK",
  Ac: "AC",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export type QueryEntriesCountryCode2 = OpenEnum<
  typeof QueryEntriesCountryCode2
>;

export type QueryEntriesEntryValuePhoneNumber = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor12;
  /**
   * The raw, original phone number, as inputted.
   */
  originalPhoneNumber: string;
  /**
   * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
   */
  countryCode: QueryEntriesCountryCode2;
  phoneNumber: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "phone-number";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType11 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType11 = OpenEnum<
  typeof QueryEntriesCreatedByActorType11
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor11 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType11 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValuePersonalName = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor11;
  /**
   * The first name.
   */
  firstName: string;
  /**
   * The last name.
   */
  lastName: string;
  /**
   * The full name.
   */
  fullName: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "personal-name";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType10 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType10 = OpenEnum<
  typeof QueryEntriesCreatedByActorType10
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor10 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType10 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueNumber = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor10;
  /**
   * Numbers are persisted as 64 bit floats.
   */
  value: number;
  /**
   * The attribute type of the value.
   */
  attributeType: "number";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType9 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType9 = OpenEnum<
  typeof QueryEntriesCreatedByActorType9
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor9 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType9 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code for the country this location is in.
 */
export const QueryEntriesCountryCode1 = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
  Bq: "BQ",
  Kp: "KP",
  Sx: "SX",
  Xk: "XK",
  Ac: "AC",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code for the country this location is in.
 */
export type QueryEntriesCountryCode1 = OpenEnum<
  typeof QueryEntriesCountryCode1
>;

export type QueryEntriesEntryValueLocation = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor9;
  /**
   * The first line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line1: string | null;
  /**
   * The second line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line2: string | null;
  /**
   * The third line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line3: string | null;
  /**
   * The fourth line of the address. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.
   */
  line4: string | null;
  /**
   * The town, neighborhood or area the location is in.
   */
  locality: string | null;
  /**
   * The state, county, province or region that the location is in.
   */
  region: string | null;
  /**
   * The postcode or zip code for the location. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  postcode: string | null;
  /**
   * The ISO 3166-1 alpha-2 country code for the country this location is in.
   */
  countryCode: QueryEntriesCountryCode1 | null;
  /**
   * The latitude of the location. Validated by the regular expression `/^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?)$/`. Values are stored with up to 9 decimal places of precision. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  latitude: string | null;
  /**
   * The longitude of the location. Validated by the regular expression `/^[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$/`. Values are stored with up to 9 decimal places of precision. Note that this value is not currently represented in the UI but will be persisted and readable through API calls.}
   */
  longitude: string | null;
  /**
   * The attribute type of the value.
   */
  attributeType: "location";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType8 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType8 = OpenEnum<
  typeof QueryEntriesCreatedByActorType8
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor8 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType8 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The type of interaction e.g. calendar or email.
 */
export const QueryEntriesInteractionType = {
  CalendarEvent: "calendar-event",
  Call: "call",
  ChatThread: "chat-thread",
  Email: "email",
  InPersonMeeting: "in-person-meeting",
  Meeting: "meeting",
} as const;
/**
 * The type of interaction e.g. calendar or email.
 */
export type QueryEntriesInteractionType = OpenEnum<
  typeof QueryEntriesInteractionType
>;

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesOwnerActorType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesOwnerActorType = OpenEnum<
  typeof QueryEntriesOwnerActorType
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesOwnerActor = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesOwnerActorType | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueInteraction = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor8;
  /**
   * The type of interaction e.g. calendar or email.
   */
  interactionType: QueryEntriesInteractionType;
  /**
   * When the interaction occurred.
   */
  interactedAt: Date;
  /**
   * The actor that created this value.
   */
  ownerActor: QueryEntriesOwnerActor;
  /**
   * The attribute type of the value.
   */
  attributeType: "interaction";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType7 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType7 = OpenEnum<
  typeof QueryEntriesCreatedByActorType7
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor7 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType7 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueRecordReference = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor7;
  /**
   * A slug identifying the object that the referenced record belongs to.
   */
  targetObject: string;
  /**
   * A UUID to identify the referenced record.
   */
  targetRecordId: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "record-reference";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType6 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType6 = OpenEnum<
  typeof QueryEntriesCreatedByActorType6
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor6 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType6 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueEmailAddress = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor6;
  originalEmailAddress: string;
  emailAddress: string;
  emailDomain: string;
  emailRootDomain: string;
  emailLocalSpecifier: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "email-address";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType5 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType5 = OpenEnum<
  typeof QueryEntriesCreatedByActorType5
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor5 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType5 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueDomain = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor5;
  domain: string;
  rootDomain: string;
  /**
   * The attribute type of the value.
   */
  attributeType: "domain";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType4 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType4 = OpenEnum<
  typeof QueryEntriesCreatedByActorType4
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor4 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType4 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueDate = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor4;
  /**
   * The attribute type of the value.
   */
  attributeType: "date";
  /**
   * A date represents a single calendar year, month and day, independent of timezone. If hours, months, seconds or timezones are provided, they will be trimmed. For example, "2023" and "2023-01" will be coerced into "2023-01-01", and "2023-01-02", "2023-01-02T13:00", "2023-01-02T14:00:00", "2023-01-02T15:00:00.000000000", and "2023-01-02T15:00:00.000000000+02:00" will all be coerced to "2023-01-02". If a timezone is provided that would result in a different calendar date in UTC, the date will be coerced to UTC and then the timezone component will be trimmed. For example, the value "2023-01-02T23:00:00-10:00" will be returned as "2023-01-03". The maximum date is "9999-12-31".
   */
  value: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType3 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType3 = OpenEnum<
  typeof QueryEntriesCreatedByActorType3
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor3 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType3 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The ISO4217 currency code representing the currency that the value is stored in.
 */
export const QueryEntriesCurrencyCode = {
  Ars: "ARS",
  Aud: "AUD",
  Brl: "BRL",
  Bgn: "BGN",
  Cad: "CAD",
  Clp: "CLP",
  Cny: "CNY",
  Cop: "COP",
  Czk: "CZK",
  Dkk: "DKK",
  Eur: "EUR",
  Fjd: "FJD",
  Hkd: "HKD",
  Huf: "HUF",
  Isk: "ISK",
  Inr: "INR",
  Ils: "ILS",
  Jpy: "JPY",
  Kes: "KES",
  Krw: "KRW",
  Myr: "MYR",
  Mxn: "MXN",
  Ntd: "NTD",
  Nzd: "NZD",
  Ngn: "NGN",
  Nok: "NOK",
  Xpf: "XPF",
  Pen: "PEN",
  Php: "PHP",
  Pln: "PLN",
  Gbp: "GBP",
  Rwf: "RWF",
  Sar: "SAR",
  Sgd: "SGD",
  Zar: "ZAR",
  Sek: "SEK",
  Chf: "CHF",
  Thb: "THB",
  Aed: "AED",
  Uyu: "UYU",
  Usd: "USD",
} as const;
/**
 * The ISO4217 currency code representing the currency that the value is stored in.
 */
export type QueryEntriesCurrencyCode = OpenEnum<
  typeof QueryEntriesCurrencyCode
>;

export type QueryEntriesEntryValueCurrency = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor3;
  /**
   * A numerical representation of the currency value. A decimal with a max of 4 decimal places.
   */
  currencyValue: number;
  /**
   * The ISO4217 currency code representing the currency that the value is stored in.
   */
  currencyCode?: QueryEntriesCurrencyCode | null | undefined;
  /**
   * The attribute type of the value.
   */
  attributeType: "currency";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType2 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType2 = OpenEnum<
  typeof QueryEntriesCreatedByActorType2
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor2 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType2 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

export type QueryEntriesEntryValueCheckbox = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor2;
  /**
   * A boolean representing whether the checkbox is checked or not. The string values 'true' and 'false' are also accepted.
   */
  value: boolean;
  /**
   * The attribute type of the value.
   */
  attributeType: "checkbox";
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesCreatedByActorType1 = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesCreatedByActorType1 = OpenEnum<
  typeof QueryEntriesCreatedByActorType1
>;

/**
 * The actor that created this value.
 */
export type QueryEntriesCreatedByActor1 = {
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: QueryEntriesCreatedByActorType1 | null | undefined;
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
};

/**
 * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
 */
export const QueryEntriesReferencedActorType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
 */
export type QueryEntriesReferencedActorType = OpenEnum<
  typeof QueryEntriesReferencedActorType
>;

export type QueryEntriesEntryValueActorReference = {
  /**
   * The point in time at which this value was made "active". `active_from` can be considered roughly analogous to `created_at`.
   */
  activeFrom: Date;
  /**
   * The point in time at which this value was deactivated. If `null`, the value is active.
   */
  activeUntil: Date | null;
  /**
   * The actor that created this value.
   */
  createdByActor: QueryEntriesCreatedByActor1;
  /**
   * The type of the referenced actor. [Read more information on actor types here](/docs/actors).
   */
  referencedActorType: QueryEntriesReferencedActorType;
  /**
   * The ID of the referenced actor.
   */
  referencedActorId: string | null;
  /**
   * The attribute type of the value.
   */
  attributeType: "actor-reference";
};

export type QueryEntriesEntryValueUnion =
  | QueryEntriesEntryValueActorReference
  | QueryEntriesEntryValueCheckbox
  | QueryEntriesEntryValueCurrency
  | QueryEntriesEntryValueDate
  | QueryEntriesEntryValueDomain
  | QueryEntriesEntryValueEmailAddress
  | QueryEntriesEntryValueRecordReference
  | QueryEntriesEntryValueInteraction
  | QueryEntriesEntryValueLocation
  | QueryEntriesEntryValueNumber
  | QueryEntriesEntryValuePersonalName
  | QueryEntriesEntryValuePhoneNumber
  | QueryEntriesEntryValueStatus
  | QueryEntriesEntryValueRating
  | QueryEntriesEntryValueSelect
  | QueryEntriesEntryValueText
  | QueryEntriesEntryValueTimestamp
  | discriminatedUnionTypes.Unknown<"attributeType">;

export type QueryEntriesData = {
  id: QueryEntriesId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: {
    [k: string]: Array<
      | QueryEntriesEntryValueActorReference
      | QueryEntriesEntryValueCheckbox
      | QueryEntriesEntryValueCurrency
      | QueryEntriesEntryValueDate
      | QueryEntriesEntryValueDomain
      | QueryEntriesEntryValueEmailAddress
      | QueryEntriesEntryValueRecordReference
      | QueryEntriesEntryValueInteraction
      | QueryEntriesEntryValueLocation
      | QueryEntriesEntryValueNumber
      | QueryEntriesEntryValuePersonalName
      | QueryEntriesEntryValuePhoneNumber
      | QueryEntriesEntryValueStatus
      | QueryEntriesEntryValueRating
      | QueryEntriesEntryValueSelect
      | QueryEntriesEntryValueText
      | QueryEntriesEntryValueTimestamp
      | discriminatedUnionTypes.Unknown<"attributeType">
    >;
  };
};

/**
 * Success
 */
export type QueryEntriesResponse = {
  data: Array<QueryEntriesData>;
};

/** @internal */
export const QueryEntriesDirection2$outboundSchema: z.ZodMiniEnum<
  typeof QueryEntriesDirection2
> = z.enum(QueryEntriesDirection2);

/** @internal */
export type QueryEntriesSort2$Outbound = {
  direction: string;
  path: Array<Array<string>>;
  field?: string | undefined;
};

/** @internal */
export const QueryEntriesSort2$outboundSchema: z.ZodMiniType<
  QueryEntriesSort2$Outbound,
  QueryEntriesSort2
> = z.object({
  direction: QueryEntriesDirection2$outboundSchema,
  path: z.array(z.array(z.string())),
  field: z.optional(z.string()),
});

export function queryEntriesSort2ToJSON(
  queryEntriesSort2: QueryEntriesSort2,
): string {
  return JSON.stringify(
    QueryEntriesSort2$outboundSchema.parse(queryEntriesSort2),
  );
}

/** @internal */
export const QueryEntriesDirection1$outboundSchema: z.ZodMiniEnum<
  typeof QueryEntriesDirection1
> = z.enum(QueryEntriesDirection1);

/** @internal */
export type QueryEntriesSort1$Outbound = {
  direction: string;
  attribute: string;
  field?: string | undefined;
};

/** @internal */
export const QueryEntriesSort1$outboundSchema: z.ZodMiniType<
  QueryEntriesSort1$Outbound,
  QueryEntriesSort1
> = z.object({
  direction: QueryEntriesDirection1$outboundSchema,
  attribute: z.string(),
  field: z.optional(z.string()),
});

export function queryEntriesSort1ToJSON(
  queryEntriesSort1: QueryEntriesSort1,
): string {
  return JSON.stringify(
    QueryEntriesSort1$outboundSchema.parse(queryEntriesSort1),
  );
}

/** @internal */
export type QueryEntriesSortUnion$Outbound =
  | QueryEntriesSort1$Outbound
  | QueryEntriesSort2$Outbound;

/** @internal */
export const QueryEntriesSortUnion$outboundSchema: z.ZodMiniType<
  QueryEntriesSortUnion$Outbound,
  QueryEntriesSortUnion
> = smartUnion([
  z.lazy(() => QueryEntriesSort1$outboundSchema),
  z.lazy(() => QueryEntriesSort2$outboundSchema),
]);

export function queryEntriesSortUnionToJSON(
  queryEntriesSortUnion: QueryEntriesSortUnion,
): string {
  return JSON.stringify(
    QueryEntriesSortUnion$outboundSchema.parse(queryEntriesSortUnion),
  );
}

/** @internal */
export type QueryEntriesRequestBody$Outbound = {
  filter?: { [k: string]: any } | undefined;
  filter_view_id?: string | undefined;
  sorts?:
    | Array<QueryEntriesSort1$Outbound | QueryEntriesSort2$Outbound>
    | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const QueryEntriesRequestBody$outboundSchema: z.ZodMiniType<
  QueryEntriesRequestBody$Outbound,
  QueryEntriesRequestBody
> = z.pipe(
  z.object({
    filter: z.optional(z.record(z.string(), z.any())),
    filterViewId: z.optional(z.string()),
    sorts: z.optional(z.array(smartUnion([
      z.lazy(() => QueryEntriesSort1$outboundSchema),
      z.lazy(() =>
        QueryEntriesSort2$outboundSchema
      ),
    ]))),
    limit: z.optional(z.number()),
    offset: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      filterViewId: "filter_view_id",
    });
  }),
);

export function queryEntriesRequestBodyToJSON(
  queryEntriesRequestBody: QueryEntriesRequestBody,
): string {
  return JSON.stringify(
    QueryEntriesRequestBody$outboundSchema.parse(queryEntriesRequestBody),
  );
}

/** @internal */
export type QueryEntriesRequest$Outbound = {
  list: string;
  body: QueryEntriesRequestBody$Outbound;
};

/** @internal */
export const QueryEntriesRequest$outboundSchema: z.ZodMiniType<
  QueryEntriesRequest$Outbound,
  QueryEntriesRequest
> = z.object({
  list: z.string(),
  body: z.lazy(() => QueryEntriesRequestBody$outboundSchema),
});

export function queryEntriesRequestToJSON(
  queryEntriesRequest: QueryEntriesRequest,
): string {
  return JSON.stringify(
    QueryEntriesRequest$outboundSchema.parse(queryEntriesRequest),
  );
}

/** @internal */
export const QueryEntriesId$inboundSchema: z.ZodMiniType<
  QueryEntriesId,
  unknown
> = z.pipe(
  z.object({
    workspace_id: types.string(),
    list_id: types.string(),
    entry_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "list_id": "listId",
      "entry_id": "entryId",
    });
  }),
);

export function queryEntriesIdFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesId' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType17$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType17,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType17);

/** @internal */
export const QueryEntriesCreatedByActor17$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor17,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType17$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor17FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor17, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor17$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor17' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueTimestamp$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueTimestamp,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor17$inboundSchema),
    attribute_type: types.literal("timestamp"),
    value: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueTimestampFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueTimestamp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueTimestamp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueTimestamp' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType16$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType16,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType16);

/** @internal */
export const QueryEntriesCreatedByActor16$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor16,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType16$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor16FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor16, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor16$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor16' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueText$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueText,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor16$inboundSchema),
    value: types.string(),
    attribute_type: types.literal("text"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueTextFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueText, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueText$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueText' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType15$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType15,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType15);

/** @internal */
export const QueryEntriesCreatedByActor15$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor15,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType15$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor15FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor15, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor15$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor15' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueSelect$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueSelect,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor15$inboundSchema),
    option: models.SelectOption$inboundSchema,
    attribute_type: types.literal("select"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueSelectFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueSelect, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueSelect$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueSelect' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType14$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType14,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType14);

/** @internal */
export const QueryEntriesCreatedByActor14$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor14,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType14$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor14FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor14, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor14$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor14' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueRating$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueRating,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor14$inboundSchema),
    value: types.number(),
    attribute_type: types.literal("rating"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueRatingFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueRating, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueRating$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueRating' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType13$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType13,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType13);

/** @internal */
export const QueryEntriesCreatedByActor13$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor13,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType13$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor13FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor13, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor13$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor13' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueStatus$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueStatus,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor13$inboundSchema),
    status: models.Status$inboundSchema,
    attribute_type: types.literal("status"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueStatusFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueStatus, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueStatus$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueStatus' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType12$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType12,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType12);

/** @internal */
export const QueryEntriesCreatedByActor12$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor12,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType12$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor12FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor12, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor12$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor12' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCountryCode2$inboundSchema: z.ZodMiniType<
  QueryEntriesCountryCode2,
  unknown
> = openEnums.inboundSchema(QueryEntriesCountryCode2);

/** @internal */
export const QueryEntriesEntryValuePhoneNumber$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValuePhoneNumber,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor12$inboundSchema),
    original_phone_number: types.string(),
    country_code: QueryEntriesCountryCode2$inboundSchema,
    phone_number: types.string(),
    attribute_type: types.literal("phone-number"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "original_phone_number": "originalPhoneNumber",
      "country_code": "countryCode",
      "phone_number": "phoneNumber",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValuePhoneNumberFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValuePhoneNumber, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValuePhoneNumber$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValuePhoneNumber' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType11$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType11,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType11);

/** @internal */
export const QueryEntriesCreatedByActor11$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor11,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType11$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor11FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor11, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor11$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor11' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValuePersonalName$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValuePersonalName,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor11$inboundSchema),
    first_name: types.string(),
    last_name: types.string(),
    full_name: types.string(),
    attribute_type: types.literal("personal-name"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "first_name": "firstName",
      "last_name": "lastName",
      "full_name": "fullName",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValuePersonalNameFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValuePersonalName, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryEntriesEntryValuePersonalName$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValuePersonalName' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType10$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType10,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType10);

/** @internal */
export const QueryEntriesCreatedByActor10$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor10,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType10$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor10FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor10, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor10$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor10' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueNumber$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueNumber,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor10$inboundSchema),
    value: types.number(),
    attribute_type: types.literal("number"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueNumberFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueNumber, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueNumber$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueNumber' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType9$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType9,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType9);

/** @internal */
export const QueryEntriesCreatedByActor9$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor9,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType9$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor9FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor9, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor9$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor9' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCountryCode1$inboundSchema: z.ZodMiniType<
  QueryEntriesCountryCode1,
  unknown
> = openEnums.inboundSchema(QueryEntriesCountryCode1);

/** @internal */
export const QueryEntriesEntryValueLocation$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueLocation,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor9$inboundSchema),
    line_1: types.nullable(types.string()),
    line_2: types.nullable(types.string()),
    line_3: types.nullable(types.string()),
    line_4: types.nullable(types.string()),
    locality: types.nullable(types.string()),
    region: types.nullable(types.string()),
    postcode: types.nullable(types.string()),
    country_code: types.nullable(QueryEntriesCountryCode1$inboundSchema),
    latitude: types.nullable(types.string()),
    longitude: types.nullable(types.string()),
    attribute_type: types.literal("location"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "line_1": "line1",
      "line_2": "line2",
      "line_3": "line3",
      "line_4": "line4",
      "country_code": "countryCode",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueLocationFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueLocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueLocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueLocation' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType8$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType8,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType8);

/** @internal */
export const QueryEntriesCreatedByActor8$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor8,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType8$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor8FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor8, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor8$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor8' from JSON`,
  );
}

/** @internal */
export const QueryEntriesInteractionType$inboundSchema: z.ZodMiniType<
  QueryEntriesInteractionType,
  unknown
> = openEnums.inboundSchema(QueryEntriesInteractionType);

/** @internal */
export const QueryEntriesOwnerActorType$inboundSchema: z.ZodMiniType<
  QueryEntriesOwnerActorType,
  unknown
> = openEnums.inboundSchema(QueryEntriesOwnerActorType);

/** @internal */
export const QueryEntriesOwnerActor$inboundSchema: z.ZodMiniType<
  QueryEntriesOwnerActor,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesOwnerActorType$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesOwnerActorFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesOwnerActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesOwnerActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesOwnerActor' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueInteraction$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueInteraction,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor8$inboundSchema),
    interaction_type: QueryEntriesInteractionType$inboundSchema,
    interacted_at: types.date(),
    owner_actor: z.lazy(() => QueryEntriesOwnerActor$inboundSchema),
    attribute_type: types.literal("interaction"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "interaction_type": "interactionType",
      "interacted_at": "interactedAt",
      "owner_actor": "ownerActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueInteractionFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueInteraction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueInteraction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueInteraction' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType7$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType7,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType7);

/** @internal */
export const QueryEntriesCreatedByActor7$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor7,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType7$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor7FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor7, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor7$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor7' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueRecordReference$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueRecordReference,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor7$inboundSchema),
    target_object: types.string(),
    target_record_id: types.string(),
    attribute_type: types.literal("record-reference"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "target_object": "targetObject",
      "target_record_id": "targetRecordId",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueRecordReferenceFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueRecordReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryEntriesEntryValueRecordReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueRecordReference' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType6$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType6,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType6);

/** @internal */
export const QueryEntriesCreatedByActor6$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor6,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType6$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor6FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor6, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor6$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor6' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueEmailAddress$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueEmailAddress,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor6$inboundSchema),
    original_email_address: types.string(),
    email_address: types.string(),
    email_domain: types.string(),
    email_root_domain: types.string(),
    email_local_specifier: types.string(),
    attribute_type: types.literal("email-address"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "original_email_address": "originalEmailAddress",
      "email_address": "emailAddress",
      "email_domain": "emailDomain",
      "email_root_domain": "emailRootDomain",
      "email_local_specifier": "emailLocalSpecifier",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueEmailAddressFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueEmailAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryEntriesEntryValueEmailAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueEmailAddress' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType5$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType5,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType5);

/** @internal */
export const QueryEntriesCreatedByActor5$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor5,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType5$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor5FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor5, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor5$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor5' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueDomain$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueDomain,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor5$inboundSchema),
    domain: types.string(),
    root_domain: types.string(),
    attribute_type: types.literal("domain"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "root_domain": "rootDomain",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueDomainFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueDomain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueDomain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueDomain' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType4$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType4,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType4);

/** @internal */
export const QueryEntriesCreatedByActor4$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor4,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType4$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor4FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor4, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor4$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor4' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueDate$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueDate,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor4$inboundSchema),
    attribute_type: types.literal("date"),
    value: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueDateFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueDate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueDate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueDate' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType3$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType3,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType3);

/** @internal */
export const QueryEntriesCreatedByActor3$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor3,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType3$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor3FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor3' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCurrencyCode$inboundSchema: z.ZodMiniType<
  QueryEntriesCurrencyCode,
  unknown
> = openEnums.inboundSchema(QueryEntriesCurrencyCode);

/** @internal */
export const QueryEntriesEntryValueCurrency$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueCurrency,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor3$inboundSchema),
    currency_value: types.number(),
    currency_code: z.optional(
      z.nullable(QueryEntriesCurrencyCode$inboundSchema),
    ),
    attribute_type: types.literal("currency"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "currency_value": "currencyValue",
      "currency_code": "currencyCode",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueCurrencyFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueCurrency, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueCurrency$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueCurrency' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType2$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType2,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType2);

/** @internal */
export const QueryEntriesCreatedByActor2$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor2,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType2$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor2FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor2' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueCheckbox$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueCheckbox,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor2$inboundSchema),
    value: types.boolean(),
    attribute_type: types.literal("checkbox"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueCheckboxFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueCheckbox, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueCheckbox$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueCheckbox' from JSON`,
  );
}

/** @internal */
export const QueryEntriesCreatedByActorType1$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActorType1,
  unknown
> = openEnums.inboundSchema(QueryEntriesCreatedByActorType1);

/** @internal */
export const QueryEntriesCreatedByActor1$inboundSchema: z.ZodMiniType<
  QueryEntriesCreatedByActor1,
  unknown
> = z.object({
  type: z.optional(z.nullable(QueryEntriesCreatedByActorType1$inboundSchema)),
  id: z.optional(z.nullable(types.string())),
});

export function queryEntriesCreatedByActor1FromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesCreatedByActor1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesCreatedByActor1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesCreatedByActor1' from JSON`,
  );
}

/** @internal */
export const QueryEntriesReferencedActorType$inboundSchema: z.ZodMiniType<
  QueryEntriesReferencedActorType,
  unknown
> = openEnums.inboundSchema(QueryEntriesReferencedActorType);

/** @internal */
export const QueryEntriesEntryValueActorReference$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueActorReference,
  unknown
> = z.pipe(
  z.object({
    active_from: types.date(),
    active_until: types.nullable(types.date()),
    created_by_actor: z.lazy(() => QueryEntriesCreatedByActor1$inboundSchema),
    referenced_actor_type: QueryEntriesReferencedActorType$inboundSchema,
    referenced_actor_id: types.nullable(types.string()),
    attribute_type: types.literal("actor-reference"),
  }),
  z.transform((v) => {
    return remap$(v, {
      "active_from": "activeFrom",
      "active_until": "activeUntil",
      "created_by_actor": "createdByActor",
      "referenced_actor_type": "referencedActorType",
      "referenced_actor_id": "referencedActorId",
      "attribute_type": "attributeType",
    });
  }),
);

export function queryEntriesEntryValueActorReferenceFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueActorReference, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      QueryEntriesEntryValueActorReference$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueActorReference' from JSON`,
  );
}

/** @internal */
export const QueryEntriesEntryValueUnion$inboundSchema: z.ZodMiniType<
  QueryEntriesEntryValueUnion,
  unknown
> = discriminatedUnion("attribute_type", {
  ["actor-reference"]: z.lazy(() =>
    QueryEntriesEntryValueActorReference$inboundSchema
  ),
  checkbox: z.lazy(() => QueryEntriesEntryValueCheckbox$inboundSchema),
  currency: z.lazy(() => QueryEntriesEntryValueCurrency$inboundSchema),
  date: z.lazy(() => QueryEntriesEntryValueDate$inboundSchema),
  domain: z.lazy(() => QueryEntriesEntryValueDomain$inboundSchema),
  ["email-address"]: z.lazy(() =>
    QueryEntriesEntryValueEmailAddress$inboundSchema
  ),
  ["record-reference"]: z.lazy(() =>
    QueryEntriesEntryValueRecordReference$inboundSchema
  ),
  interaction: z.lazy(() => QueryEntriesEntryValueInteraction$inboundSchema),
  location: z.lazy(() => QueryEntriesEntryValueLocation$inboundSchema),
  number: z.lazy(() => QueryEntriesEntryValueNumber$inboundSchema),
  ["personal-name"]: z.lazy(() =>
    QueryEntriesEntryValuePersonalName$inboundSchema
  ),
  ["phone-number"]: z.lazy(() =>
    QueryEntriesEntryValuePhoneNumber$inboundSchema
  ),
  status: z.lazy(() => QueryEntriesEntryValueStatus$inboundSchema),
  rating: z.lazy(() => QueryEntriesEntryValueRating$inboundSchema),
  select: z.lazy(() => QueryEntriesEntryValueSelect$inboundSchema),
  text: z.lazy(() => QueryEntriesEntryValueText$inboundSchema),
  timestamp: z.lazy(() => QueryEntriesEntryValueTimestamp$inboundSchema),
}, { outputPropertyName: "attributeType" });

export function queryEntriesEntryValueUnionFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesEntryValueUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesEntryValueUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesEntryValueUnion' from JSON`,
  );
}

/** @internal */
export const QueryEntriesData$inboundSchema: z.ZodMiniType<
  QueryEntriesData,
  unknown
> = z.pipe(
  z.object({
    id: z.lazy(() => QueryEntriesId$inboundSchema),
    parent_record_id: types.string(),
    parent_object: types.string(),
    created_at: types.string(),
    entry_values: z.record(
      z.string(),
      z.array(discriminatedUnion("attribute_type", {
        ["actor-reference"]: z.lazy(() =>
          QueryEntriesEntryValueActorReference$inboundSchema
        ),
        checkbox: z.lazy(() => QueryEntriesEntryValueCheckbox$inboundSchema),
        currency: z.lazy(() => QueryEntriesEntryValueCurrency$inboundSchema),
        date: z.lazy(() => QueryEntriesEntryValueDate$inboundSchema),
        domain: z.lazy(() => QueryEntriesEntryValueDomain$inboundSchema),
        ["email-address"]: z.lazy(() =>
          QueryEntriesEntryValueEmailAddress$inboundSchema
        ),
        ["record-reference"]: z.lazy(() =>
          QueryEntriesEntryValueRecordReference$inboundSchema
        ),
        interaction: z.lazy(() =>
          QueryEntriesEntryValueInteraction$inboundSchema
        ),
        location: z.lazy(() => QueryEntriesEntryValueLocation$inboundSchema),
        number: z.lazy(() => QueryEntriesEntryValueNumber$inboundSchema),
        ["personal-name"]: z.lazy(() =>
          QueryEntriesEntryValuePersonalName$inboundSchema
        ),
        ["phone-number"]: z.lazy(() =>
          QueryEntriesEntryValuePhoneNumber$inboundSchema
        ),
        status: z.lazy(() => QueryEntriesEntryValueStatus$inboundSchema),
        rating: z.lazy(() => QueryEntriesEntryValueRating$inboundSchema),
        select: z.lazy(() => QueryEntriesEntryValueSelect$inboundSchema),
        text: z.lazy(() => QueryEntriesEntryValueText$inboundSchema),
        timestamp: z.lazy(() => QueryEntriesEntryValueTimestamp$inboundSchema),
      }, { outputPropertyName: "attributeType" })),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "parent_record_id": "parentRecordId",
      "parent_object": "parentObject",
      "created_at": "createdAt",
      "entry_values": "entryValues",
    });
  }),
);

export function queryEntriesDataFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesData' from JSON`,
  );
}

/** @internal */
export const QueryEntriesResponse$inboundSchema: z.ZodMiniType<
  QueryEntriesResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => QueryEntriesData$inboundSchema)),
});

export function queryEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<QueryEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => QueryEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'QueryEntriesResponse' from JSON`,
  );
}
