/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RequestAsWorkspaceMember2 = {
  type: "workspace-member";
  emailAddress: string;
};

export type RequestAsWorkspaceMember1 = {
  type: "workspace-member";
  workspaceMemberId: string;
};

export type RequestAsWorkspace = {
  type: "workspace";
};

/**
 * Specifies the context in which to perform the search. Use 'workspace' to return all search results or specify a workspace member to limit results to what one specific person in your workspace can see.
 */
export type RequestAs =
  | RequestAsWorkspaceMember1
  | RequestAsWorkspaceMember2
  | RequestAsWorkspace;

export type SearchRecordsRequest = {
  /**
   * Query string to search for. An empty string returns a default set of results.
   */
  query: string;
  /**
   * The maximum number of results to return. Defaults to 25.
   */
  limit?: number | undefined;
  /**
   * Specifies which objects to filter results by. At least one object must be specified. Accepts object slugs or IDs.
   */
  objects: Array<string>;
  /**
   * Specifies the context in which to perform the search. Use 'workspace' to return all search results or specify a workspace member to limit results to what one specific person in your workspace can see.
   */
  requestAs:
    | RequestAsWorkspaceMember1
    | RequestAsWorkspaceMember2
    | RequestAsWorkspace;
};

export type SearchRecordsId3 = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type DataCompanies = {
  id: SearchRecordsId3;
  /**
   * A human-readable label for the record. Present on records from all objects.
   */
  recordText: string;
  /**
   * The image for the record.
   */
  recordImage: string | null;
  /**
   * The slug of the object this record belongs to.
   */
  objectSlug: "companies";
  /**
   * The company's domains.
   */
  domains: Array<string>;
};

export type SearchRecordsId2 = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type DataPeople = {
  id: SearchRecordsId2;
  /**
   * A human-readable label for the record. Present on records from all objects.
   */
  recordText: string;
  /**
   * The image for the record.
   */
  recordImage: string | null;
  /**
   * The slug of the object this record belongs to.
   */
  objectSlug: "people";
  /**
   * The person's email addresses.
   */
  emailAddresses: Array<string>;
  /**
   * The person's phone numbers.
   */
  phoneNumbers: Array<string>;
};

export type SearchRecordsId1 = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type SearchRecordsData = {
  id: SearchRecordsId1;
  /**
   * A human-readable label for the record. Present on records from all objects.
   */
  recordText: string;
  /**
   * The image for the record.
   */
  recordImage: string | null;
  /**
   * The slug of the object this record belongs to.
   */
  objectSlug: string;
};

export type SearchRecordsDataUnion =
  | DataPeople
  | DataCompanies
  | SearchRecordsData;

/**
 * Success
 */
export type SearchRecordsResponse = {
  data: Array<DataPeople | DataCompanies | SearchRecordsData>;
};

/** @internal */
export type RequestAsWorkspaceMember2$Outbound = {
  type: "workspace-member";
  email_address: string;
};

/** @internal */
export const RequestAsWorkspaceMember2$outboundSchema: z.ZodMiniType<
  RequestAsWorkspaceMember2$Outbound,
  RequestAsWorkspaceMember2
> = z.pipe(
  z.object({
    type: z.literal("workspace-member"),
    emailAddress: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      emailAddress: "email_address",
    });
  }),
);

export function requestAsWorkspaceMember2ToJSON(
  requestAsWorkspaceMember2: RequestAsWorkspaceMember2,
): string {
  return JSON.stringify(
    RequestAsWorkspaceMember2$outboundSchema.parse(requestAsWorkspaceMember2),
  );
}

/** @internal */
export type RequestAsWorkspaceMember1$Outbound = {
  type: "workspace-member";
  workspace_member_id: string;
};

/** @internal */
export const RequestAsWorkspaceMember1$outboundSchema: z.ZodMiniType<
  RequestAsWorkspaceMember1$Outbound,
  RequestAsWorkspaceMember1
> = z.pipe(
  z.object({
    type: z.literal("workspace-member"),
    workspaceMemberId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      workspaceMemberId: "workspace_member_id",
    });
  }),
);

export function requestAsWorkspaceMember1ToJSON(
  requestAsWorkspaceMember1: RequestAsWorkspaceMember1,
): string {
  return JSON.stringify(
    RequestAsWorkspaceMember1$outboundSchema.parse(requestAsWorkspaceMember1),
  );
}

/** @internal */
export type RequestAsWorkspace$Outbound = {
  type: "workspace";
};

/** @internal */
export const RequestAsWorkspace$outboundSchema: z.ZodMiniType<
  RequestAsWorkspace$Outbound,
  RequestAsWorkspace
> = z.object({
  type: z.literal("workspace"),
});

export function requestAsWorkspaceToJSON(
  requestAsWorkspace: RequestAsWorkspace,
): string {
  return JSON.stringify(
    RequestAsWorkspace$outboundSchema.parse(requestAsWorkspace),
  );
}

/** @internal */
export type RequestAs$Outbound =
  | RequestAsWorkspaceMember1$Outbound
  | RequestAsWorkspaceMember2$Outbound
  | RequestAsWorkspace$Outbound;

/** @internal */
export const RequestAs$outboundSchema: z.ZodMiniType<
  RequestAs$Outbound,
  RequestAs
> = smartUnion([
  z.lazy(() => RequestAsWorkspaceMember1$outboundSchema),
  z.lazy(() => RequestAsWorkspaceMember2$outboundSchema),
  z.lazy(() => RequestAsWorkspace$outboundSchema),
]);

export function requestAsToJSON(requestAs: RequestAs): string {
  return JSON.stringify(RequestAs$outboundSchema.parse(requestAs));
}

/** @internal */
export type SearchRecordsRequest$Outbound = {
  query: string;
  limit: number;
  objects: Array<string>;
  request_as:
    | RequestAsWorkspaceMember1$Outbound
    | RequestAsWorkspaceMember2$Outbound
    | RequestAsWorkspace$Outbound;
};

/** @internal */
export const SearchRecordsRequest$outboundSchema: z.ZodMiniType<
  SearchRecordsRequest$Outbound,
  SearchRecordsRequest
> = z.pipe(
  z.object({
    query: z.string(),
    limit: z._default(z.number(), 25),
    objects: z.array(z.string()),
    requestAs: smartUnion([
      z.lazy(() => RequestAsWorkspaceMember1$outboundSchema),
      z.lazy(() => RequestAsWorkspaceMember2$outboundSchema),
      z.lazy(() => RequestAsWorkspace$outboundSchema),
    ]),
  }),
  z.transform((v) => {
    return remap$(v, {
      requestAs: "request_as",
    });
  }),
);

export function searchRecordsRequestToJSON(
  searchRecordsRequest: SearchRecordsRequest,
): string {
  return JSON.stringify(
    SearchRecordsRequest$outboundSchema.parse(searchRecordsRequest),
  );
}

/** @internal */
export const SearchRecordsId3$inboundSchema: z.ZodMiniType<
  SearchRecordsId3,
  unknown
> = z.pipe(
  z.object({
    workspace_id: types.string(),
    object_id: types.string(),
    record_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "object_id": "objectId",
      "record_id": "recordId",
    });
  }),
);

export function searchRecordsId3FromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsId3, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsId3$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsId3' from JSON`,
  );
}

/** @internal */
export const DataCompanies$inboundSchema: z.ZodMiniType<
  DataCompanies,
  unknown
> = z.pipe(
  z.object({
    id: z.lazy(() => SearchRecordsId3$inboundSchema),
    record_text: types.string(),
    record_image: types.nullable(types.string()),
    object_slug: types.literal("companies"),
    domains: z.array(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "record_text": "recordText",
      "record_image": "recordImage",
      "object_slug": "objectSlug",
    });
  }),
);

export function dataCompaniesFromJSON(
  jsonString: string,
): SafeParseResult<DataCompanies, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataCompanies$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataCompanies' from JSON`,
  );
}

/** @internal */
export const SearchRecordsId2$inboundSchema: z.ZodMiniType<
  SearchRecordsId2,
  unknown
> = z.pipe(
  z.object({
    workspace_id: types.string(),
    object_id: types.string(),
    record_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "object_id": "objectId",
      "record_id": "recordId",
    });
  }),
);

export function searchRecordsId2FromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsId2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsId2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsId2' from JSON`,
  );
}

/** @internal */
export const DataPeople$inboundSchema: z.ZodMiniType<DataPeople, unknown> = z
  .pipe(
    z.object({
      id: z.lazy(() => SearchRecordsId2$inboundSchema),
      record_text: types.string(),
      record_image: types.nullable(types.string()),
      object_slug: types.literal("people"),
      email_addresses: z.array(types.string()),
      phone_numbers: z.array(types.string()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "record_text": "recordText",
        "record_image": "recordImage",
        "object_slug": "objectSlug",
        "email_addresses": "emailAddresses",
        "phone_numbers": "phoneNumbers",
      });
    }),
  );

export function dataPeopleFromJSON(
  jsonString: string,
): SafeParseResult<DataPeople, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DataPeople$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DataPeople' from JSON`,
  );
}

/** @internal */
export const SearchRecordsId1$inboundSchema: z.ZodMiniType<
  SearchRecordsId1,
  unknown
> = z.pipe(
  z.object({
    workspace_id: types.string(),
    object_id: types.string(),
    record_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "object_id": "objectId",
      "record_id": "recordId",
    });
  }),
);

export function searchRecordsId1FromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsId1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsId1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsId1' from JSON`,
  );
}

/** @internal */
export const SearchRecordsData$inboundSchema: z.ZodMiniType<
  SearchRecordsData,
  unknown
> = z.pipe(
  z.object({
    id: z.lazy(() => SearchRecordsId1$inboundSchema),
    record_text: types.string(),
    record_image: types.nullable(types.string()),
    object_slug: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "record_text": "recordText",
      "record_image": "recordImage",
      "object_slug": "objectSlug",
    });
  }),
);

export function searchRecordsDataFromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsData' from JSON`,
  );
}

/** @internal */
export const SearchRecordsDataUnion$inboundSchema: z.ZodMiniType<
  SearchRecordsDataUnion,
  unknown
> = smartUnion([
  z.lazy(() => DataPeople$inboundSchema),
  z.lazy(() => DataCompanies$inboundSchema),
  z.lazy(() => SearchRecordsData$inboundSchema),
]);

export function searchRecordsDataUnionFromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsDataUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsDataUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsDataUnion' from JSON`,
  );
}

/** @internal */
export const SearchRecordsResponse$inboundSchema: z.ZodMiniType<
  SearchRecordsResponse,
  unknown
> = z.object({
  data: z.array(
    smartUnion([
      z.lazy(() => DataPeople$inboundSchema),
      z.lazy(() => DataCompanies$inboundSchema),
      z.lazy(() => SearchRecordsData$inboundSchema),
    ]),
  ),
});

export function searchRecordsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SearchRecordsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SearchRecordsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SearchRecordsResponse' from JSON`,
  );
}
