/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Whether the attribute is on an object or a list.
 */
export const UpdateAttributeSelectOptionTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attribute is on an object or a list.
 */
export type UpdateAttributeSelectOptionTarget = ClosedEnum<
  typeof UpdateAttributeSelectOptionTarget
>;

export type UpdateAttributeSelectOptionData = {
  /**
   * The Title of the select option
   */
  title?: string | undefined;
  /**
   * Whether or not to archive the select option. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
   */
  isArchived?: boolean | undefined;
};

export type UpdateAttributeSelectOptionRequestBody = {
  data: UpdateAttributeSelectOptionData;
};

export type UpdateAttributeSelectOptionRequest = {
  /**
   * Whether the attribute is on an object or a list.
   */
  target: UpdateAttributeSelectOptionTarget;
  identifier: string;
  attribute: string;
  option: string;
  body: UpdateAttributeSelectOptionRequestBody;
};

/**
 * Success
 */
export type UpdateAttributeSelectOptionResponse = {
  data: models.SelectOption;
};

/** @internal */
export const UpdateAttributeSelectOptionTarget$outboundSchema: z.ZodMiniEnum<
  typeof UpdateAttributeSelectOptionTarget
> = z.enum(UpdateAttributeSelectOptionTarget);

/** @internal */
export type UpdateAttributeSelectOptionData$Outbound = {
  title?: string | undefined;
  is_archived?: boolean | undefined;
};

/** @internal */
export const UpdateAttributeSelectOptionData$outboundSchema: z.ZodMiniType<
  UpdateAttributeSelectOptionData$Outbound,
  UpdateAttributeSelectOptionData
> = z.pipe(
  z.object({
    title: z.optional(z.string()),
    isArchived: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      isArchived: "is_archived",
    });
  }),
);

export function updateAttributeSelectOptionDataToJSON(
  updateAttributeSelectOptionData: UpdateAttributeSelectOptionData,
): string {
  return JSON.stringify(
    UpdateAttributeSelectOptionData$outboundSchema.parse(
      updateAttributeSelectOptionData,
    ),
  );
}

/** @internal */
export type UpdateAttributeSelectOptionRequestBody$Outbound = {
  data: UpdateAttributeSelectOptionData$Outbound;
};

/** @internal */
export const UpdateAttributeSelectOptionRequestBody$outboundSchema:
  z.ZodMiniType<
    UpdateAttributeSelectOptionRequestBody$Outbound,
    UpdateAttributeSelectOptionRequestBody
  > = z.object({
    data: z.lazy(() => UpdateAttributeSelectOptionData$outboundSchema),
  });

export function updateAttributeSelectOptionRequestBodyToJSON(
  updateAttributeSelectOptionRequestBody:
    UpdateAttributeSelectOptionRequestBody,
): string {
  return JSON.stringify(
    UpdateAttributeSelectOptionRequestBody$outboundSchema.parse(
      updateAttributeSelectOptionRequestBody,
    ),
  );
}

/** @internal */
export type UpdateAttributeSelectOptionRequest$Outbound = {
  target: string;
  identifier: string;
  attribute: string;
  option: string;
  body: UpdateAttributeSelectOptionRequestBody$Outbound;
};

/** @internal */
export const UpdateAttributeSelectOptionRequest$outboundSchema: z.ZodMiniType<
  UpdateAttributeSelectOptionRequest$Outbound,
  UpdateAttributeSelectOptionRequest
> = z.object({
  target: UpdateAttributeSelectOptionTarget$outboundSchema,
  identifier: z.string(),
  attribute: z.string(),
  option: z.string(),
  body: z.lazy(() => UpdateAttributeSelectOptionRequestBody$outboundSchema),
});

export function updateAttributeSelectOptionRequestToJSON(
  updateAttributeSelectOptionRequest: UpdateAttributeSelectOptionRequest,
): string {
  return JSON.stringify(
    UpdateAttributeSelectOptionRequest$outboundSchema.parse(
      updateAttributeSelectOptionRequest,
    ),
  );
}

/** @internal */
export const UpdateAttributeSelectOptionResponse$inboundSchema: z.ZodMiniType<
  UpdateAttributeSelectOptionResponse,
  unknown
> = z.object({
  data: models.SelectOption$inboundSchema,
});

export function updateAttributeSelectOptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAttributeSelectOptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAttributeSelectOptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAttributeSelectOptionResponse' from JSON`,
  );
}
